//! Term-level nat arithmetic / comparison / coercion.
//!
//! `natRec` is defined first as a `def` (ε-style) with the standard
//! primitive-recursor uniqueness predicate as its `tm`. Every other
//! op (`natAdd`, `natMul`, `natSub`, …) is a `let` definition whose
//! body is a direct lambda built from `natRec`. Specifications like
//!
//! ```text
//! ∀n m. natAdd 0 m = m ∧ natAdd (succ n) m = succ (natAdd n m)
//! ```
//!
//! are therefore **theorems** about these definitions, not the
//! definitions themselves — they're provable by `eq_reflection` on
//! the body plus the natRec equations.
//!
//! `natDiv` is a `let` definition too — the explicit course-of-values
//! recursion fixpoint (see [`nat_div_body`]), so it is choice-free (no
//! Hilbert ε beyond the shared `natRec`); `natMod` is `λn m. n - (n/m)*m`.
//! The byte/bit ops still default to `tm = None`, awaiting their
//! definitions in follow-up commits.

use crate::hol;
use crate::term::{Term, Type};

use super::canonical::Canonical;
use super::sigs;

// ============================================================================
// natSucc / natPred — TermSpec constants. No body; the certificate path
// matches on them to evaluate closed-form applications.
// ============================================================================

/// `succ : nat → nat` — the **primitive** successor constructor
/// ([`Term::succ`] / [`crate::TermKind::Succ`]). Not a `defs`
/// spec: `nat` is freely generated by `0` / `succ`, so `succ` is a
/// first-class kernel term and the kernel commits to it directly — the
/// freeness rules ([`crate::Thm::succ_eq_elim`] / [`crate::Thm::zero_eq_succ_elim`])
/// and closed-literal reduction match on [`crate::TermKind::Succ`]
/// rather than on a spec handle. Kept here (and re-exported as
/// `defs::nat_succ`) so existing call sites that build `succ` keep
/// working unchanged.
pub fn nat_succ() -> Term {
    Term::succ()
}

fn nat_pred_body() -> Term {
    // pred ≔ λn. natRec 0 (λk _. k) n   (saturating predecessor)
    let k = Term::free("k", Type::nat());
    let g = hol::pub_abs("k", Type::nat(), hol::pub_abs("_", Type::nat(), k)); // λk _. k
    let n = Term::free("n", Type::nat());
    let body = Term::app(
        Term::app(Term::app(nat_rec(Type::nat()), hol::zero()), g),
        n,
    );
    hol::pub_abs("n", Type::nat(), body)
}

let_term! {
    /// `natPred : nat → nat` ≡ `λn. natRec 0 (λk _. k) n` — saturating
    /// predecessor. Equations: `pred 0 = 0`, `pred (S n) = n` (both
    /// provable from the `natRec` recursion equations). Closed-literal
    /// reduction still goes through the certificate path.
    nat_pred_spec, nat_pred, Canonical::NatPred, nat_pred_body()
}

// ============================================================================
// Type signatures used here
// ============================================================================

/// `nat → α → α` — the step function expected by `natRec`.
fn nat_alpha_to_alpha(alpha: &Type) -> Type {
    Type::fun(Type::nat(), Type::fun(alpha.clone(), alpha.clone()))
}

/// `α → (nat → α → α) → nat → α` — natRec's full type with `α` free.
fn nat_rec_ty() -> Type {
    let alpha = Type::tfree("a");
    Type::fun(
        alpha.clone(),
        Type::fun(nat_alpha_to_alpha(&alpha), Type::fun(Type::nat(), alpha)),
    )
}

// ============================================================================
// natRec — primitive recursor
// ============================================================================

/// `λr. ∀z f. r z f 0 = z ∧ ∀n. r z f (succ n) = f n (r z f n)`.
fn nat_rec_predicate() -> Term {
    let alpha = Type::tfree("a");
    let f_ty = nat_alpha_to_alpha(&alpha);
    let r_ty = Type::fun(
        alpha.clone(),
        Type::fun(f_ty.clone(), Type::fun(Type::nat(), alpha.clone())),
    );

    let r = Term::free("r", r_ty.clone());
    let z = Term::free("z", alpha.clone());
    let f = Term::free("f", f_ty.clone());

    // r z f 0 = z
    let r_z_f = Term::app(Term::app(r.clone(), z.clone()), f.clone());
    let r_z_f_0 = Term::app(r_z_f.clone(), hol::zero());
    let base_eq = hol::hol_eq(r_z_f_0, z.clone());

    // ∀n. r z f (succ n) = f n (r z f n)
    let n = Term::free("n", Type::nat());
    let succ_n = Term::app(hol::succ_fn(), n.clone());
    let r_z_f_succ_n = Term::app(r_z_f.clone(), succ_n);
    let r_z_f_n = Term::app(r_z_f, n.clone());
    let f_n_rec = Term::app(Term::app(f.clone(), n.clone()), r_z_f_n);
    let step_eq = hol::hol_eq(r_z_f_succ_n, f_n_rec);
    let step = hol::hol_forall("n", Type::nat(), step_eq);

    let body = hol::hol_and(base_eq, step);
    let body_zf = hol::hol_forall("z", alpha, hol::hol_forall("f", f_ty, body));
    hol::pub_abs("r", r_ty, body_zf)
}

poly_spec_term! {
    /// `natRec : 'a → (nat → 'a → 'a) → nat → 'a`. The standard
    /// primitive recursor; every nat-typed operation derives from
    /// applying `natRec` at the appropriate `α`.
    nat_rec_spec, nat_rec(alpha), Canonical::NatRec, nat_rec_ty(), nat_rec_predicate()
}

// ============================================================================
// iter — n-fold function iteration.
//
// iter n f a ≔ natRec a (λ_:nat. f) n
//
// Equations (provable from the definition + natRec equations):
//   iter 0     f a = a
//   iter (S n) f a = f (iter n f a)
//
// Useful corollary (provable by induction on n):
//   iter (S n) f a = iter n f (f a)
//
// Every binary nat op below (add/mul/sub/pow/shl/shr) factors through
// iter: each step ignores `n`, so iter is the more idiomatic choice
// than the full natRec.
// ============================================================================

fn iter_body() -> Term {
    let alpha = Type::tfree("a");
    let alpha_to_alpha = Type::fun(alpha.clone(), alpha.clone());

    let n = Term::free("n", Type::nat());
    let f = Term::free("f", alpha_to_alpha.clone());
    let a = Term::free("a", alpha.clone());

    // step: λ_:nat. f
    let step = hol::pub_abs("_", Type::nat(), f.clone());

    let rec_at_alpha = nat_rec(alpha.clone());
    let app1 = Term::app(rec_at_alpha, a.clone());
    let app2 = Term::app(app1, step);
    let body = Term::app(app2, n.clone());

    let lam_a = hol::pub_abs("a", alpha.clone(), body);
    let lam_f = hol::pub_abs("f", alpha_to_alpha, lam_a);
    hol::pub_abs("n", Type::nat(), lam_f)
}

poly_let_term! {
    /// `iter : nat → ('a → 'a) → 'a → 'a`. Defined as
    /// `λn f a. natRec a (λ_. f) n`. Equations: `iter 0 f a = a`,
    /// `iter (S n) f a = f (iter n f a)`. Corollary:
    /// `iter (S n) f a = iter n f (f a)`.
    iter_spec, iter(alpha), Canonical::Iter, iter_body()
}

/// Build a body of the shape `λn m. iter[nat] n $step_fn $seed` —
/// iterate `step_fn` on `seed`, `n` times. The moved catalogue ops in
/// `covalence-hol-eval::defs::nat` carry the two-sided (`n`/`m` count)
/// twin of this helper; only the `n`-counted form is needed for the
/// residual `natAdd`.
fn iter_binary(step_fn: Term, seed: Term) -> Term {
    let n = Term::free("n", Type::nat());

    let app1 = Term::app(iter(Type::nat()), n.clone());
    let app2 = Term::app(app1, step_fn);
    let body = Term::app(app2, seed);

    let lam_m = hol::pub_abs("m", Type::nat(), body);
    hol::pub_abs("n", Type::nat(), lam_m)
}

fn nat_add_body() -> Term {
    // natAdd n m ≔ iter n succ m
    iter_binary(hol::succ_fn(), Term::free("m", Type::nat()))
}

let_term! {
    /// `natAdd : nat → nat → nat` ≡ `λn m. iter n succ m`.
    /// Equations: `natAdd 0 m = m`, `natAdd (S n) m = S (natAdd n m)`.
    nat_add_spec, nat_add, Canonical::NatAdd, nat_add_body()
}

// ============================================================================
// natLe / natLt — selector-predicate definitions (booleans, no clean
// natRec route without if-then-else infrastructure).
// ============================================================================

/// Predicate for a `nat → nat → bool` comparison: four clauses on
/// `cmp(0, 0)`, `cmp(0, S m)`, `cmp(S n, 0)`, `cmp(S n, S m) = cmp(n, m)`.
fn nat_cmp_predicate(zero_zero: bool, zero_succ: bool, succ_zero: bool) -> Term {
    let cmp_ty = sigs::nat_nat_to_bool();
    let cmp = Term::free("cmp", cmp_ty.clone());

    let zero = hol::zero();
    let lit = Term::bool_lit;

    let cmp_00 = hol::hol_eq(
        Term::app(Term::app(cmp.clone(), zero.clone()), zero.clone()),
        lit(zero_zero),
    );

    let m = Term::free("m", Type::nat());
    let succ_m = Term::app(hol::succ_fn(), m.clone());
    let cmp_0_succm = hol::hol_eq(
        Term::app(Term::app(cmp.clone(), zero.clone()), succ_m.clone()),
        lit(zero_succ),
    );
    let cmp_0_succ = hol::hol_forall("m", Type::nat(), cmp_0_succm);

    let n = Term::free("n", Type::nat());
    let succ_n = Term::app(hol::succ_fn(), n.clone());
    let cmp_succn_0 = hol::hol_eq(
        Term::app(Term::app(cmp.clone(), succ_n.clone()), zero),
        lit(succ_zero),
    );
    let cmp_succ_0 = hol::hol_forall("n", Type::nat(), cmp_succn_0);

    let n2 = Term::free("n", Type::nat());
    let m2 = Term::free("m", Type::nat());
    let succ_n2 = Term::app(hol::succ_fn(), n2.clone());
    let succ_m2 = Term::app(hol::succ_fn(), m2.clone());
    let cmp_succ_succ = hol::hol_eq(
        Term::app(Term::app(cmp.clone(), succ_n2), succ_m2),
        Term::app(Term::app(cmp.clone(), n2), m2),
    );
    let cmp_ss_m = hol::hol_forall("m", Type::nat(), cmp_succ_succ);
    let cmp_ss = hol::hol_forall("n", Type::nat(), cmp_ss_m);

    let body = hol::hol_and(
        cmp_00,
        hol::hol_and(cmp_0_succ, hol::hol_and(cmp_succ_0, cmp_ss)),
    );
    hol::pub_abs("cmp", cmp_ty, body)
}

spec_term! {
    /// `natLe : nat → nat → bool`. Selector predicate:
    /// `le 0 0 = T`, `∀m. le 0 (S m) = T`, `∀n. le (S n) 0 = F`,
    /// `∀n m. le (S n) (S m) = le n m`.
    nat_le_spec, nat_le, Canonical::NatLe,
    sigs::nat_nat_to_bool(), nat_cmp_predicate(true, true, false)
}

spec_term! {
    /// `natLt : nat → nat → bool`. Selector predicate:
    /// `lt 0 0 = F`, `∀m. lt 0 (S m) = T`, `∀n. lt (S n) 0 = F`,
    /// `∀n m. lt (S n) (S m) = lt n m`.
    nat_lt_spec, nat_lt, Canonical::NatLt,
    sigs::nat_nat_to_bool(), nat_cmp_predicate(false, true, false)
}
