//! The fine-grained TCB: one **sound** [`Rule`] ZST per HOL inference
//! step, generated by the [`core_rules!`] catalogue macro.
//!
//! Each rule's `decide` reads its premises' propositions through the public
//! `pure::Thm::prop()` accessor, checks the rule's side conditions, and **derives**
//! the conclusion (it never accepts a caller-supplied conclusion). Every rule is
//! therefore *sound on all inputs*, so admitting its `TypeId` is exactly what
//! confers soundness — this is the admits-only milestone (see `lang.rs`).
//!
//! The macro emits, per rule and from a SINGLE source list:
//! - the ZST,
//! - a typed `prove` fn (the old `Thm` method's term-building + side-condition
//!   logic, moved verbatim),
//! - the tier-generic [`Rule<L>`](Rule) impl for every [`HolTier`]
//!   (`decide = prove(..).map_err(to_pure)`),
//! - its [`RuleRecord`] in [`CORE_MANIFEST`], and
//! - its [`core_admits`] arm,
//!
//! so `admits()` and the static manifest can never drift.
//!
//! The public `Thm` methods in `thm/mod.rs` / `thm/typedef.rs` are thin glue: they
//! pull the inner `pure::Thm`s out of the premise `core::Thm`s, call
//! [`covalence_pure::apply`] on the hot path, and — only on the cold failure path —
//! re-run `Rule::prove` to recover the typed [`Error`] for the existing tests.

use std::any::TypeId;
use std::fmt;

use smol_str::SmolStr;

use covalence_pure::{
    App, Error as PureError, LangMeta, Language, Manifest, Rule, RuleMeta, RuleRecord, Val,
};

use crate::ctx::Ctx;
use crate::error::{Error, Result};
use crate::hol;
use crate::subst::{
    close_var, collect_term_tvars, has_free_var_typed, open, shift_by, subst_free,
    subst_tfree_in_term, uses_bound_outer,
};
use crate::term::{Def, FreshId, Term, TermKind, Type, TypeKind, Var};
use crate::ty::{TypeList, TypeSpec};

use super::lang::{CoreLang, CoreProp, HolTier, IsThm};

/// An unforgeable premise: a `pure::Thm` carrying an `IsThm`-headed proposition,
/// only mintable via an admitted rule (see `lang.rs`). Generic over the
/// [`HolTier`] so the same rule catalogue serves every tier (premises are taken
/// at the *minting* tier; a lower-tier theorem enters via
/// [`Thm::lift`](super::Thm::lift)).
pub(crate) type Prem<L = CoreLang> = covalence_pure::Thm<L, CoreProp>;

/// Read a premise's sequent `(Γ, φ)` by reference (reading never mints).
pub(crate) fn parts<L: Language>(p: &Prem<L>) -> (&Ctx, &Term) {
    let q = p.prop();
    (&q.1.0.0, &q.1.1.0)
}

/// The shared well-typedness check behind the sequent floor: the
/// conclusion and every hypothesis must be well-typed at kind `bool`.
/// Called by [`seq`] (every sequent rule) and by
/// [`crate::Thm::from_pure`] (the seam's landing constructor), so both
/// paths into a kernel `Thm` enforce the same floor.
pub(crate) fn check_sequent(hyps: &Ctx, concl: &Term) -> Result<()> {
    let ty = concl.type_of()?;
    if !ty.is_bool() {
        return Err(Error::NotBool(ty));
    }
    for h in hyps {
        let hty = h.type_of()?;
        if !hty.is_bool() {
            return Err(Error::NotBool(hty));
        }
    }
    Ok(())
}

/// The soundness floor (the old `Thm::build` body): the conclusion and every
/// hypothesis must be well-typed at kind `bool` ([`check_sequent`]), then wrap
/// into the `IsThm` proposition. Every rule bottoms out here.
fn seq(hyps: Ctx, concl: Term) -> Result<CoreProp> {
    check_sequent(&hyps, &concl)?;
    Ok(App(IsThm, (Val(hyps), Val(concl))))
}

/// Lower a typed [`Error`] into pure's stringly-typed `RuleFailed`. Only used on
/// `decide`'s error path; the public glue recovers the typed error separately.
fn to_pure(e: Error) -> PureError {
    PureError::RuleFailed(e.to_string())
}

/// One rule ⇒ ZST + typed `prove` + `Rule` impl + admits arm + `RuleRecord`, all
/// in lockstep from one source list, so `admits()`/`MANIFEST` cannot drift.
///
/// One section feeding the manifest/admits emission:
/// - `rules { … }` — the sequent rules: `Concl = CoreProp`, minted through the
///   `seq` well-typedness floor; `Rule<L>` for every [`HolTier`] (premises are
///   `Prem<L>` at the minting tier), so a higher tier that admits the rule
///   mints it directly.
///
/// (The former `raw { … }` toHOL/certificate section and the `canon { … }`
/// [`covalence_pure::CanonRule`] section moved to `covalence-hol-eval`'s
/// `eval_rules!` — the `CoreEval` tier hosts the computation-backed rules, so
/// `Thm<CoreLang>` carries no computation TCB.)
macro_rules! core_rules {
    (
        rules { $( $(#[$d:meta])* $N:ident($($ty:ty),* $(,)?) = |$p:pat_param, $l:pat_param| $b:block )+ }
    ) => {
        $(
            $(#[$d])*
            #[derive(Clone, Copy)]
            pub(crate) struct $N;

            impl $N {
                // The inner closure is load-bearing: rule bodies use early
                // `return Err(..)`, which must exit to the closure's
                // `Result<(Ctx, Term)>` (distinct from `prove`'s `Result<CoreProp>`,
                // which `seq` bridges) — so this is NOT a redundant closure call.
                #[allow(clippy::redundant_closure_call)]
                pub(crate) fn prove<L: HolTier>($p: ($($ty,)*), $l: &L) -> Result<CoreProp> {
                    let (hyps, concl) = (|| -> Result<(Ctx, Term)> { $b })()?;
                    seq(hyps, concl)
                }
            }

            // Generic over the tier: the SAME sound derivation serves every
            // `HolTier` (the rule never reads the language), and the gate stays
            // `admits` on the rule's own `TypeId` — a tier admits a HOL rule
            // only by enumerating it in its own manifest.
            impl<L: HolTier> Rule<L> for $N {
                type Input = ($($ty,)*);
                type Concl = CoreProp;
                fn decide(
                    self,
                    input: Self::Input,
                    lang: &L,
                ) -> core::result::Result<CoreProp, PureError> {
                    Self::prove(input, lang).map_err(to_pure)
                }
            }
        )+

        /// The static TCB manifest for [`CoreLang`] — one [`RuleRecord`] per
        /// admitted rule, emitted from the same source list as
        /// [`core_admits`]. The single parent is the
        /// [`covalence_pure_eval::Builtins`] manifest (embedded by value), so
        /// `tree(CoreLang)` — core's rules plus the enumerable native
        /// computation — is readable from this one item. `pub const` (re-exported
        /// through [`crate::seam`]) so a downstream tier language owning its own
        /// rules (`CoreEval` in `covalence-hol-eval`) can embed it as a parent in
        /// its own manifest; reading it mints nothing.
        pub const CORE_MANIFEST: Manifest = Manifest {
            ty: TypeId::of::<CoreLang>(),
            extends: &[],
            admits: &[
                $( RuleRecord { ty: TypeId::of::<$N>(), metadata: RuleMeta }, )+
            ],
            metadata: LangMeta,
        };

        /// The admits predicate for [`CoreLang`], emitted from the same lists as
        /// [`CORE_MANIFEST`]: `true` exactly for the admitted rule TypeIds.
        /// `pub` (re-exported through [`crate::seam`]) so a downstream tier that
        /// `extends` [`CoreLang`] can delegate its inherited-rule gate here;
        /// querying the gate mints nothing.
        pub fn core_admits(r: TypeId) -> bool {
            $( r == TypeId::of::<$N>() )||+
        }

        /// Untrusted name projection of [`CORE_MANIFEST`] (same order, 1:1) —
        /// the source-level rule idents, for the `docs/deps/core-manifest.txt`
        /// golden. Identity is always the `TypeId`.
        #[cfg(test)]
        pub(crate) fn core_rule_names() -> Vec<(&'static str, TypeId)> {
            vec![
                $( (stringify!($N), TypeId::of::<$N>()), )+
            ]
        }
    };
}

/// Public-method glue: apply on the hot path, recover the typed [`Error`] cold.
///
/// Tier-generic: expands against the `L: HolTier` in scope at the call site
/// (the `impl<L: HolTier> Thm<L>` blocks), minting at `L::default()` — so the
/// same glue serves `Thm<CoreLang>` and any future tier that admits the rule.
///
/// `$apply_input` is built from `Arc`-clones (moved into `apply`); `$prove_input`
/// reuses the originals for the cold re-run of `prove`. `decide == prove.map_err`,
/// so `apply` fails iff `prove` fails on the same input ⇒ the cold `unwrap_err`
/// never panics on a real rule failure.
macro_rules! mint {
    ($R:ident, $apply_input:expr, $prove_input:expr) => {
        match covalence_pure::apply(L::default(), $R, $apply_input) {
            Ok(inner) => Ok(crate::thm::Thm(inner)),
            Err(_) => Err($R::prove($prove_input, &L::default()).unwrap_err()),
        }
    };
}

pub(crate) use mint;

core_rules! {
    rules {
    // ================= Group A: equality + congruence =================

    /// `⊢ t = t`.
    Refl(Term) = |(t,), _| {
        let _ = t.type_of()?;
        Ok((Ctx::new(), hol::hol_eq(t.clone(), t)))
    }

    /// `Γ ⊢ b = a`, given `Γ ⊢ a = b`.
    Sym(Prem<L>) = |(t,), _| {
        let (hyps, concl) = parts(&t);
        let (a, b, alpha) = super::parse_hol_eq_at(concl)?;
        Ok((hyps.clone(), hol::hol_eq_at(alpha.clone(), b.clone(), a.clone())))
    }

    /// `Γ ∪ Δ ⊢ s = u`, given `Γ ⊢ s = t` and `Δ ⊢ t = u`.
    Trans(Prem<L>, Prem<L>) = |(a, b), _| {
        let (ha, ca) = parts(&a);
        let (hb, cb) = parts(&b);
        let (s, t1, alpha) = super::parse_hol_eq_at(ca)?;
        let (t2, u) = super::parse_hol_eq(cb)?;
        if t1 != t2 {
            return Err(Error::TransMiddleMismatch {
                left: format!("{}", t1),
                right: format!("{}", t2),
            });
        }
        Ok((ha.union(hb), hol::hol_eq_at(alpha.clone(), s.clone(), u.clone())))
    }

    /// `Γ ∪ Δ ⊢ f x = g y`, given `Γ ⊢ f = g` and `Δ ⊢ x = y`.
    MkComb(Prem<L>, Prem<L>) = |(f_thm, arg), _| {
        let (hf, cf) = parts(&f_thm);
        let (hx, cx) = parts(&arg);
        let (f, g, funty) = super::parse_hol_eq_at(cf)?;
        let (x, y) = super::parse_hol_eq(cx)?;
        let TypeKind::Fun(_dom, cod) = funty.kind() else {
            return Err(Error::NotFunction(funty.clone()));
        };
        let cod = cod.clone();
        let lhs = Term::app(f.clone(), x.clone());
        let rhs = Term::app(g.clone(), y.clone());
        Ok((hf.union(hx), hol::hol_eq_at(cod, lhs, rhs)))
    }

    /// `Γ ⊢ (λx:τ. s[x]) = (λx:τ. t[x])`, given `Γ ⊢ s = t` with `(name:τ)` not
    /// free in `Γ`.
    Abs(Prem<L>, SmolStr, Type) = |(t, name, ty), _| {
        let (hyps, concl) = parts(&t);
        let (s, body_t, alpha) = super::parse_hol_eq_at(concl)?;
        let alpha = alpha.clone();
        let var = Var::new(name.as_str(), ty.clone());
        for h in hyps.iter() {
            if has_free_var_typed(h, &var) {
                return Err(Error::FreeVarInHyps { name: name.clone() });
            }
        }
        let s = s.clone();
        let body_t = body_t.clone();
        let s_abs = Term::abs(ty.clone(), close_var(&s, &var));
        let t_abs = Term::abs(ty.clone(), close_var(&body_t, &var));
        Ok((hyps.clone(), hol::hol_eq_at(Type::fun(ty, alpha), s_abs, t_abs)))
    }

    /// `⊢ (λx:τ. body) arg = body[arg/0]` — one outermost β-step.
    BetaConv(Term) = |(app,), _| {
        let TermKind::App(fun, arg) = app.kind() else {
            return Err(Error::NotApp(format!("{}", app)));
        };
        let TermKind::Abs(ty, body) = fun.kind() else {
            return Err(Error::NotAbs(format!("{}", fun)));
        };
        let arg_ty = arg.type_of()?;
        if arg_ty != *ty {
            return Err(Error::TypeMismatch { expected: ty.clone(), got: arg_ty });
        }
        // Validate the WHOLE redex, not just the argument: the abstraction
        // BODY may be ill-typed or ill-scoped (e.g. an out-of-scope Bound),
        // and `hol::hol_eq` requires a well-typed lhs — its contract says
        // inference-rule callers pre-validate. Without this, `hol_eq`'s
        // `expect` PANICKED on such input (found by the `panic_envelopes`
        // property test; a fail-stop, not a soundness hole — `build`
        // re-validates every conclusion). Strictly narrows the rule's
        // domain: inputs that previously panicked now `Err` cleanly.
        let _ = app.type_of()?;
        let rhs = open(body, arg);
        Ok((Ctx::new(), hol::hol_eq(app.clone(), rhs)))
    }

    /// `⊢ (λx:τ. f x) = f`, when `Bound(0)` does not appear free in `f`.
    EtaConv(Term) = |(abs,), _| {
        let TermKind::Abs(ty, body) = abs.kind() else {
            return Err(Error::NotAbs(format!("{}", abs)));
        };
        let TermKind::App(f, x) = body.kind() else {
            return Err(Error::EtaShape);
        };
        let TermKind::Bound(0) = x.kind() else {
            return Err(Error::EtaShape);
        };
        if uses_bound_outer(f, 0) {
            return Err(Error::EtaShape);
        }
        let _ = abs.type_of()?;
        let _ = ty;
        let f_outer = shift_by(f, -1, 0);
        Ok((Ctx::new(), hol::hol_eq(abs.clone(), f_outer)))
    }

    // ================= Group B: LF =================

    /// `{p} ⊢ p` for `p : bool`.
    Assume(Term) = |(p,), _| {
        let ty = p.type_of()?;
        if !ty.is_bool() {
            return Err(Error::NotBool(ty));
        }
        Ok((Ctx::singleton(p.clone()), p))
    }

    /// `Γ ∪ Δ ⊢ q`, given `Γ ⊢ p = q : bool` and `Δ ⊢ p`.
    EqMp(Prem<L>, Prem<L>) = |(eq_thm, p_thm), _| {
        let (heq, ceq) = parts(&eq_thm);
        let (hp, cp) = parts(&p_thm);
        let (p, q, alpha) = super::parse_hol_eq_at(ceq)?;
        if !alpha.is_bool() {
            return Err(Error::NotBool(alpha.clone()));
        }
        if *p != *cp {
            return Err(Error::ImpAntecedentMismatch {
                expected: format!("{}", p),
                got: format!("{}", cp),
            });
        }
        Ok((heq.union(hp), q.clone()))
    }

    /// `(Γ \ {q}) ∪ (Δ \ {p}) ⊢ p ⇔ q`, given `Γ ⊢ p` and `Δ ⊢ q` (both bool).
    DeductAntisym(Prem<L>, Prem<L>) = |(a, b), _| {
        let (ha, ca) = parts(&a);
        let (hb, cb) = parts(&b);
        let p_ty = ca.type_of()?;
        let q_ty = cb.type_of()?;
        if !p_ty.is_bool() {
            return Err(Error::NotBool(p_ty));
        }
        if !q_ty.is_bool() {
            return Err(Error::NotBool(q_ty));
        }
        let p = ca.clone();
        let q = cb.clone();
        let hyps_p_minus_q = ha.remove(&q);
        let hyps_q_minus_p = hb.remove(&p);
        Ok((hyps_p_minus_q.union(&hyps_q_minus_p), hol::hol_eq(p, q)))
    }

    // (The connective / quantifier rules — imp/all/and/or/not intro+elim —
    // left the kernel in stage L2: they are *derivations* over the rules
    // above, provided with identical signatures by
    // `covalence-hol-eval::derived::DerivedRules`. Zero TCB.)

    // ================= Group D: substitution =================

    /// `Γ[x:=r] ⊢ φ[x:=r]` — substitute free `(name, r.type)` by `r`.
    Inst(Prem<L>, SmolStr, Term) = |(t, name, replacement), _| {
        let (hyps, concl) = parts(&t);
        let var = Var::new(name.as_str(), replacement.type_of()?);
        let new_concl = subst_free(concl, &var, &replacement);
        let new_hyps = hyps.map(|h| subst_free(h, &var, &replacement));
        Ok((new_hyps, new_concl))
    }

    /// `Γ[α:=σ] ⊢ φ[α:=σ]`.
    InstTFree(Prem<L>, SmolStr, Type) = |(t, name, replacement), _| {
        let (hyps, concl) = parts(&t);
        let new_concl = subst_tfree_in_term(concl, name.as_str(), &replacement);
        let new_hyps = hyps.map(|h| subst_tfree_in_term(h, name.as_str(), &replacement));
        Ok((new_hyps, new_concl))
    }

    // ================= Group E: structural =================

    /// `Δ ⊢ φ`, given `Γ ⊢ φ` and `Γ ⊆ Δ`.
    Weaken(Prem<L>, Ctx) = |(t, target), _| {
        let (hyps, concl) = parts(&t);
        if !hyps.is_subset(&target) {
            return Err(Error::NotASuperset);
        }
        Ok((target, concl.clone()))
    }

    // ================= Group F: TypeSpec abs/rep laws =================

    /// `⊢ abs (rep a) = a`.
    SpecAbsRep(TypeSpec, TypeList, Term) = |(spec, args, a), _| {
        let (abs, rep, _carrier, wrapper) = super::spec_coercions(&spec, &args)?;
        let a_ty = a.type_of()?;
        if a_ty != wrapper {
            return Err(Error::TypeMismatch { expected: wrapper, got: a_ty });
        }
        let lhs = Term::app(abs, Term::app(rep, a.clone()));
        Ok((Ctx::new(), hol::hol_eq(lhs, a)))
    }

    /// `Γ ⊢ rep (abs a) = a`, given `Γ ⊢ P a` — the conditional
    /// carrier-side round-trip, in connective-free **sequent form**: the
    /// premise's conclusion is parsed as `P a` (with `P` checked, by
    /// structural equality, against the spec's instantiated selector
    /// predicate), and the equation is concluded under the same
    /// hypotheses. The old implication form `⊢ P a ⟹ rep (abs a) = a`
    /// is the zero-TCB derivation `assume` + this rule + `imp_intro`
    /// (`covalence-hol-eval::derived::DerivedRules::spec_rep_abs_fwd`).
    SpecRepAbsFwd(TypeSpec, TypeList, Prem<L>) = |(spec, args, prem), _| {
        let (abs, rep, carrier, _wrapper) = super::spec_coercions(&spec, &args)?;
        let pred = super::subtype_pred(&spec, &args, &carrier)?;
        let (hyps, concl) = parts(&prem);
        let TermKind::App(prem_pred, a) = concl.kind() else {
            return Err(Error::NotApp(format!("{}", concl)));
        };
        if *prem_pred != pred {
            return Err(Error::ConnectiveRule(format!(
                "spec_rep_abs_intro: premise head {prem_pred} is not the selector predicate {pred}"
            )));
        }
        let a = a.clone();
        let eq = hol::hol_eq_at(carrier, Term::app(rep, Term::app(abs, a.clone())), a);
        Ok((hyps.clone(), eq))
    }

    /// `⊢ rep (abs a) = a ⟹ (P a ∨ ¬∃x. P x)`.
    ///
    /// **Stays connective-built (not sequent-reshaped):** the `∨`-of-`¬∃`
    /// disjunction is what makes the rule *witness-free* (sound even for
    /// an empty `P`, so `TypeSpec`s postulate nothing) — a sequent form
    /// would need a non-emptiness premise, reintroducing the witness this
    /// rule exists to avoid. It therefore keeps building `⟹/∨/¬/∃` from
    /// the `defs::logic` catalogue until the ε/rep/abs endgame (L4)
    /// re-homes the `TypeSpec` machinery wholesale.
    SpecRepAbsBack(TypeSpec, TypeList, Term) = |(spec, args, a), _| {
        let (abs, rep, carrier, _wrapper) = super::spec_coercions(&spec, &args)?;
        let a_ty = a.type_of()?;
        if a_ty != carrier {
            return Err(Error::TypeMismatch { expected: carrier, got: a_ty });
        }
        let pred = super::subtype_pred(&spec, &args, &carrier)?;
        let prem = hol::hol_eq(Term::app(rep, Term::app(abs, a.clone())), a.clone());
        let pa = Term::app(pred.clone(), a);
        let some_x = hol::hol_exists(
            "x",
            carrier.clone(),
            Term::app(pred, Term::free("x", carrier)),
        );
        let disj = hol::hol_or(pa, hol::hol_not(some_x));
        Ok((Ctx::new(), hol::hol_imp(prem, disj)))
    }

    /// `Γ ⊢ p t`, given `Γ ⊢ p w`, for a def-style `TermSpec` leaf
    /// `t = Spec(spec, args)` with selector predicate `p` — in
    /// connective-free **sequent form**: the premise's conclusion is
    /// parsed as `p w` (with `p` checked, by structural equality,
    /// against the spec's instantiated selector predicate), and `p t`
    /// is concluded under the same hypotheses. The old implication form
    /// `⊢ p w ⟹ p t` is the zero-TCB derivation `assume` + this rule +
    /// `imp_intro` (`covalence-hol-eval::derived::DerivedRules::spec_ax`).
    SpecAx(Prem<L>, Term) = |(prem, t), _| {
        let (spec, args) = match t.kind() {
            TermKind::Spec(spec, args) => (spec.clone(), args.clone()),
            _ => return Err(Error::NotASpec),
        };
        let declared_ty = spec.ty().ok_or(Error::SpecHasNoBody)?.clone();
        let body = spec.tm().ok_or(Error::SpecHasNoBody)?.clone();
        let body_ty = body.type_of()?;
        if body_ty != Type::fun(declared_ty.clone(), Type::bool()) {
            return Err(Error::SpecIsLetStyle);
        }
        let tvars = declared_ty.free_tvars();
        let pred = super::inst_spec_tvars(&body, &tvars, &args);
        let (hyps, concl) = parts(&prem);
        let TermKind::App(prem_pred, _w) = concl.kind() else {
            return Err(Error::NotApp(format!("{}", concl)));
        };
        if *prem_pred != pred {
            return Err(Error::ConnectiveRule(format!(
                "spec_intro: premise head {prem_pred} is not the spec's selector predicate {pred}"
            )));
        }
        Ok((hyps.clone(), Term::app(pred, t.clone())))
    }

    // ================= Group A': definitional unfolding =================
    //
    // (Closed-form literal *computation* is NOT here: it lives in the
    // per-family certificate rules below, computed by `covalence-pure-eval`
    // and driven by the untrusted `covalence-hol-eval`. `UnfoldTermSpec` is
    // sound definitional unfolding tied to `TermKind::Spec` and survives
    // until the `defs/` catalogue re-homes.)

    /// `⊢ Spec(spec, args) = subst(spec.tm, tvars, args)` for a let-style spec.
    UnfoldTermSpec(Term) = |(t,), _| {
        let (spec, args) = match t.kind() {
            TermKind::Spec(spec, args) => (spec.clone(), args.clone()),
            _ => return Err(Error::NotASpec),
        };
        let declared_ty = spec.ty().ok_or(Error::SpecHasNoBody)?.clone();
        let body = spec.tm().ok_or(Error::SpecHasNoBody)?.clone();
        let body_ty = body.type_of()?;
        if body_ty != declared_ty {
            return Err(Error::SpecIsDefStyle);
        }
        let tvars = declared_ty.free_tvars();
        let unfolded = super::inst_spec_tvars(&body, &tvars, &args);
        Ok((Ctx::new(), hol::hol_eq(t, unfolded)))
    }

    // ================= Group G: kernel primitive axioms =================

    /// `⊢ a = b` for `a, b : unit` (the singleton rule).
    UnitEq(Term, Term) = |(a, b), _| {
        let a_ty = a.type_of()?;
        if a_ty != Type::unit() {
            return Err(Error::TypeMismatch { expected: Type::unit(), got: a_ty });
        }
        let b_ty = b.type_of()?;
        if b_ty != Type::unit() {
            return Err(Error::TypeMismatch { expected: Type::unit(), got: b_ty });
        }
        Ok((Ctx::new(), hol::hol_eq(a, b)))
    }

    /// `Γ ⊢ m = n`, given `Γ ⊢ succ m = succ n` — successor injectivity
    /// in connective-free **sequent form**: the premise's conclusion is
    /// parsed as an equation between two [`Term::succ`]-headed
    /// applications, and the stripped equation is concluded under the
    /// same hypotheses. The old implication form
    /// `⊢ succ m = succ n ⟹ m = n` is the zero-TCB derivation `assume` +
    /// this rule + `imp_intro`
    /// (`covalence-hol-eval::derived::DerivedRules::succ_inj`).
    SuccInj(Prem<L>) = |(prem,), _| {
        let (hyps, concl) = parts(&prem);
        let (lhs, rhs, alpha) = super::parse_hol_eq_at(concl)?;
        let succ_arg = |t: &Term| -> Result<Term> {
            match t.kind() {
                TermKind::App(f, a) if *f == Term::succ() => Ok(a.clone()),
                _ => Err(Error::ConnectiveRule(format!(
                    "succ_eq_elim: {t} is not `succ _`"
                ))),
            }
        };
        let m = succ_arg(lhs)?;
        let n = succ_arg(rhs)?;
        Ok((hyps.clone(), hol::hol_eq_at(alpha.clone(), m, n)))
    }

    /// `Γ ⊢ q`, given `Γ ⊢ 0 = succ n` and any `q : bool` — nat
    /// no-confusion as **ex falso in sequent form**: `0` is never a
    /// successor, so hypotheses proving `0 = succ n` are inconsistent
    /// and support any conclusion. The premise's conclusion is parsed
    /// as an equation whose left side is the zero constructor (the
    /// [`Term::zero`] leaf or the `Nat` literal `⌜0⌝` — both denote
    /// zero) and whose right side is a [`Term::succ`]-application.
    /// The old negation form `⊢ ¬(0 = succ n)` is the zero-TCB
    /// derivation `assume` + this rule at `q := F` + `imp_intro` +
    /// `not_intro` (`covalence-hol-eval::derived::DerivedRules::zero_ne_succ`).
    ZeroNeSucc(Prem<L>, Term) = |(prem, q), _| {
        let (hyps, concl) = parts(&prem);
        let (lhs, rhs, _alpha) = super::parse_hol_eq_at(concl)?;
        // Both transitional zero shapes denote zero (bridged by the
        // eval-tier `ZeroLitCert`); `hol::zero()` is the `⌜0⌝` literal.
        if *lhs != Term::zero() && *lhs != hol::zero() {
            return Err(Error::ConnectiveRule(format!(
                "zero_eq_succ_elim: {lhs} is not the zero constructor"
            )));
        }
        if !matches!(rhs.kind(), TermKind::App(f, _) if *f == Term::succ()) {
            return Err(Error::ConnectiveRule(format!(
                "zero_eq_succ_elim: {rhs} is not `succ _`"
            )));
        }
        Ok((hyps.clone(), q))
    }

    // (`FalseElim` — ex falso — left the kernel in stage EG3b: with `F`
    // the defined constant `defs::fal ≡ ∀p:bool. p`, ex falso is the
    // derivation "unfold + ∀-elim at the target"
    // (`covalence-hol-eval::derived::DerivedRules::false_elim`), and the
    // transitional `Bool(false)` literal's ex falso is derived through
    // the nat-freeness bridge (`covalence-hol-eval::boolean`).)

    /// `Γ_b ∪ (Γ_s \ {p}) ⊢ p` — Peano induction on `nat`, **sequent form**
    /// (connective-free): from `Γ_b ⊢ p[0/x]` (base) and
    /// `Γ_s ⊢ p[succ x/x]` with `p ∈ Γ_s` and `x : nat` not free in
    /// `Γ_s \ {p}` (step), conclude `p` with `x` free — universal by
    /// genericity. See `Thm::nat_induct` for the audit-grade soundness
    /// argument.
    NatInduct(Prem<L>, Prem<L>, Term, SmolStr) = |(base, step, p, x), _| {
        let nat = Type::nat();
        let var = Var::new(x.as_str(), nat.clone());
        let p_ty = p.type_of()?;
        if !p_ty.is_bool() {
            return Err(Error::NotBool(p_ty));
        }
        let (base_h, base_c) = parts(&base);
        let (step_h, step_c) = parts(&step);

        // base : Γ_b ⊢ p[0/x]. (`x` MAY be free in Γ_b — see the
        // soundness docstring; the base is only consumed at the x↦0
        // instance, via the substitution lemma at the ambient valuation.)
        let zero = Term::nat_lit(covalence_types::Nat::zero());
        let p_zero = subst_free(&p, &var, &zero);
        if *base_c != p_zero {
            return Err(Error::ConnectiveRule(format!(
                "nat_induct: base conclusion {base_c} is not p[0/{x}] = {p_zero}"
            )));
        }

        // step : Γ_s ⊢ p[succ x/x] with p ∈ Γ_s (the discharged IH).
        let succ_x = Term::app(hol::succ_fn(), Term::free(x.as_str(), nat));
        let p_succ = subst_free(&p, &var, &succ_x);
        if *step_c != p_succ {
            return Err(Error::ConnectiveRule(format!(
                "nat_induct: step conclusion {step_c} is not p[succ {x}/{x}] = {p_succ}"
            )));
        }
        if !step_h.contains(&p) {
            return Err(Error::ConnectiveRule(format!(
                "nat_induct: step hypotheses do not contain the motive {p}"
            )));
        }

        // Genericity side condition (soundness-critical): `x` must not be
        // free in the RESIDUAL step hypotheses — the step must hold for
        // every value of `x`, since the induction re-instantiates it at
        // 0, 1, …, k. (`p` itself is exempt: it IS the induction
        // hypothesis being discharged.)
        let rest = step_h.remove(&p);
        for h in rest.iter() {
            if has_free_var_typed(h, &var) {
                return Err(Error::FreeVarInHyps { name: x.clone() });
            }
        }

        Ok((base_h.union(&rest), p))
    }

    // (`Lem` — excluded middle — also left the kernel in stage L2: it is
    // derivable from `SelectAx` the standard HOL way; see
    // `covalence-hol-eval::derived`'s cached LEM schema.)

    /// `Γ ⊢ p (ε p)`, given `Γ ⊢ p x` — Hilbert's choice axiom in
    /// connective-free **sequent form**: the premise's conclusion is
    /// split as the application `p x`, and `p` transfers from the
    /// witness `x` to the choice term `ε p` ([`TermKind::Select`]).
    /// The old implication form `⊢ p x ⟹ p (ε p)` (HOL Light's
    /// `SELECT_AX` instance) is the zero-TCB derivation `assume` + this
    /// rule + `imp_intro`
    /// (`covalence-hol-eval::derived::DerivedRules::select_ax`).
    SelectAx(Prem<L>) = |(prem,), _| {
        let (hyps, concl) = parts(&prem);
        let TermKind::App(p, _x) = concl.kind() else {
            return Err(Error::NotApp(format!("{}", concl)));
        };
        let p = p.clone();
        let p_ty = p.type_of()?;
        let TypeKind::Fun(dom, cod) = p_ty.kind() else {
            return Err(Error::NotFunction(p_ty));
        };
        if !cod.is_bool() {
            return Err(Error::NotBool(cod.clone()));
        }
        let choice = Term::app(Term::select_op(dom.clone()), p.clone());
        Ok((hyps.clone(), Term::app(p, choice)))
    }

    // ================= Group I: generative (fresh identity INSIDE decide) =================

    /// `⊢ Def(name, body) ≡ body` with a FRESH `Def` allocated here — never a
    /// caller-supplied `Def`, so no collision can forge `body₁ ≡ body₂`.
    Define(SmolStr, Term) = |(name, body), _| {
        let body_type = body.type_of()?;
        // No "phantom" tvars (Isabelle/Pure parity): every free tvar inside
        // `body`'s type annotations must appear in `body_type`.
        let type_tvars: std::collections::BTreeSet<SmolStr> =
            body_type.free_tvars().into_iter().collect();
        let mut body_tvars = std::collections::BTreeSet::new();
        collect_term_tvars(&body, &mut body_tvars);
        for tv in &body_tvars {
            if !type_tvars.contains(tv) {
                return Err(Error::DefPhantomTFree {
                    tvar: tv.clone(),
                    body_type,
                });
            }
        }
        let d = Def::new_internal(name, body.clone(), body_type);
        Ok((Ctx::new(), hol::hol_eq(Term::def(d), body)))
    }

    /// From a witness `Γ ⊢ P x`, mint `Γ ⊢ abs_rep ∧ (fwd ∧ back)` for a FRESH
    /// subtype τ with fresh abs/rep — all freshness allocated here. The public
    /// `new_type_definition` returns the conjunction unsplit (consumers project
    /// with `covalence-hol-eval::derived::TypeDefExt`) and shape-parses
    /// τ/abs/rep back out.
    ///
    /// **Stays connective-built (not sequent-reshaped):** one rule
    /// application mints exactly one theorem, and the three bijection laws
    /// must share the SAME fresh τ/abs/rep identity (allocated inside this
    /// `decide`, unforgeable) — so they can only leave the mint as a single
    /// `∧`-package of `∀`-closed laws. Splitting into three sequent rules
    /// would need cross-mint fresh-identity sharing, a bigger trust surface
    /// than the `∀/⟹/∧` construction. Dies/reshapes with the ε/rep/abs
    /// endgame (L4).
    NewTypeDefRule(Prem<L>, SmolStr, SmolStr) = |(witness, abs_hint, rep_hint), _| {
        let (w_hyps, w_concl) = parts(&witness);

        // 1. Decompose witness concl as `P x`.
        let TermKind::App(p, x) = w_concl.kind() else {
            return Err(Error::BadTypeDefWitness(format!("{}", w_concl)));
        };
        let p = p.clone();
        let x = x.clone();

        // 2-3. α from x; validate P : α → bool.
        let alpha = x.type_of()?;
        let p_ty = p.type_of()?;
        let TypeKind::Fun(p_dom, p_cod) = p_ty.kind() else {
            return Err(Error::NotFunction(p_ty));
        };
        if *p_dom != alpha {
            return Err(Error::TypeMismatch { expected: alpha.clone(), got: p_dom.clone() });
        }
        if !p_cod.is_bool() {
            return Err(Error::NotBool(p_cod.clone()));
        }

        // 4. tvar arity from α.
        let tvar_names = alpha.free_tvars();
        let tvar_types: Vec<Type> = tvar_names.iter().map(|n| Type::tfree(n.clone())).collect();

        // 5-6. Fresh identity (τ, abs, rep) allocated INSIDE decide: three
        //      `FreshId` tokens over the private markers below, so no caller
        //      can supply (or collide) an identity.
        let tau = Type::fresh_tycon(FreshId::new(TypeDefMarker), tvar_types);
        let abs_ty = Type::fun(alpha.clone(), tau.clone());
        let rep_ty = Type::fun(tau.clone(), alpha.clone());
        let abs = Term::fresh_const(FreshId::new(TypeDefAbsMarker { hint: abs_hint }), abs_ty);
        let rep = Term::fresh_const(FreshId::new(TypeDefRepMarker { hint: rep_hint }), rep_ty);

        // 7. The three bijection theorems, combined into one conjunction.
        //    abs_rep: ∀a:τ. abs (rep a) = a
        let a_free = Term::free("a", tau.clone());
        let abs_rep_body = hol::hol_eq(
            Term::app(abs.clone(), Term::app(rep.clone(), a_free.clone())),
            a_free,
        );
        let abs_rep_concl = hol::hol_forall("a", tau.clone(), abs_rep_body);

        let r_free = Term::free("r", alpha.clone());
        let p_at_r = Term::app(p, r_free.clone());
        let rep_abs_eq = hol::hol_eq(
            Term::app(rep.clone(), Term::app(abs.clone(), r_free.clone())),
            r_free,
        );
        //    fwd: ∀r:α. P r ⟹ rep (abs r) = r
        let fwd_concl = hol::hol_forall(
            "r",
            alpha.clone(),
            hol::hol_imp(p_at_r.clone(), rep_abs_eq.clone()),
        );
        //    back: ∀r:α. rep (abs r) = r ⟹ P r
        let back_concl = hol::hol_forall("r", alpha, hol::hol_imp(rep_abs_eq, p_at_r));

        let conj = hol::hol_and(abs_rep_concl, hol::hol_and(fwd_concl, back_concl));
        Ok((w_hyps.clone(), conj))
    }
    }
}

// ============================================================================
// new_type_definition fresh-identity markers (wrapped in `FreshId` tokens
// allocated only inside `NewTypeDefRule::decide`).
// ============================================================================
//
// The freshness itself comes from each `FreshId::new` call (a fresh `Arc`
// per token); the markers below are display-only payloads (`Debug` feeds
// `Term`/`Type` printing). They are private to this module, so even the
// marker *types* cannot be named downstream.

/// Marker inside a fresh subtype's `Type::fresh_tycon` token.
#[derive(Debug)]
struct TypeDefMarker;

/// Marker inside a typedef's `abs` constant token.
struct TypeDefAbsMarker {
    hint: SmolStr,
}

impl fmt::Debug for TypeDefAbsMarker {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.hint.is_empty() {
            write!(f, "abs")
        } else {
            write!(f, "{}", self.hint)
        }
    }
}

/// Marker inside a typedef's `rep` constant token.
struct TypeDefRepMarker {
    hint: SmolStr,
}

impl fmt::Debug for TypeDefRepMarker {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.hint.is_empty() {
            write!(f, "rep")
        } else {
            write!(f, "{}", self.hint)
        }
    }
}

// ============================================================================
// The CORE_MANIFEST golden (TCB budget): docs/deps/core-manifest.txt
// ============================================================================

#[cfg(test)]
mod manifest_tests {
    use std::any::TypeId;
    use std::collections::HashSet;

    use covalence_pure::Language;

    use super::super::lang::CoreLang;
    use super::{CORE_MANIFEST, core_admits, core_rule_names};

    const GOLDEN: &str = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../../docs/deps/core-manifest.txt"
    );

    /// Pins the name-projected rule inventory of [`CoreLang`] to
    /// `docs/deps/core-manifest.txt` — a PR that grows the admitted-rule TCB
    /// shows it in-diff. Regenerate with:
    /// `COV_REGEN_GOLDEN=1 cargo test -p covalence-core manifest_matches_golden`
    /// The transitional literal-unfolding rule and the permanent structural
    /// (succ-tower) rules pin CONTRADICTORY denotations for `toHOL n` at the
    /// `Term` sort — admitting both makes the base tier inconsistent (audit
    /// wave-1 finding: sym+trans would equate `Val(nat_lit 1)` with
    /// `Val(app(succ, nat_lit 0))`, a false definitional-Eq fact). This guard
    /// fires the moment both appear in the manifest: delete `ToHolNatVal` in
    /// the SAME commit that admits the structural rules.
    #[test]
    fn tohol_unfolding_rules_are_exclusive() {
        let names = core_rule_names();
        let transitional = names.iter().any(|(n, _)| *n == "ToHolNatVal");
        let structural = names
            .iter()
            .any(|(n, _)| n.starts_with("ToHolNatZero") || n.starts_with("ToHolNatSucc"));
        assert!(
            !(transitional && structural),
            "ToHolNatVal (literal denotation) and the structural succ-tower rules \
             must never be admitted together — they pin contradictory `toHOL` \
             denotations (see thm/SKELETONS.md)"
        );
    }

    #[test]
    fn manifest_matches_golden() {
        let names = core_rule_names();

        // Structure: the manifest is CoreLang's own; the pure-HOL tier has NO
        // parents (the historical Builtins edge moved to CoreEval with the
        // tower split — audit fix); the name projection is 1:1 and in order.
        assert_eq!(CORE_MANIFEST.ty, TypeId::of::<CoreLang>());
        assert_eq!(CORE_MANIFEST.extends.len(), 0, "pure tier: no parents");
        assert!(
            !CoreLang.extends(TypeId::of::<covalence_pure_eval::Builtins>()),
            "extends() mirrors the (empty) manifest parents — no computation TCB"
        );
        assert_eq!(names.len(), CORE_MANIFEST.admits.len(), "1:1 projection");
        for ((name, ty), rec) in names.iter().zip(CORE_MANIFEST.admits) {
            assert_eq!(*ty, rec.ty, "name/manifest order drift at {name}");
        }

        // Identity: no duplicates; admits ⟺ manifest.
        let mut tys = HashSet::new();
        for (name, ty) in &names {
            assert!(tys.insert(*ty), "duplicate rule TypeId for {name}");
            assert!(core_admits(*ty), "manifest rule {name} not admitted");
        }
        assert!(!core_admits(TypeId::of::<CoreLang>()));
        assert!(!core_admits(TypeId::of::<covalence_pure_eval::NatAdd>()));

        // The golden.
        let ours: String = names.iter().map(|(n, _)| *n).collect::<Vec<_>>().join("\n") + "\n";
        if std::env::var_os("COV_REGEN_GOLDEN").is_some() {
            std::fs::write(GOLDEN, &ours).expect("write golden");
            return;
        }
        let golden = std::fs::read_to_string(GOLDEN)
            .expect("read docs/deps/core-manifest.txt (regenerate with COV_REGEN_GOLDEN=1)");
        assert_eq!(
            golden, ours,
            "CORE_MANIFEST drifted from docs/deps/core-manifest.txt — audit \
             the diff, then regenerate with COV_REGEN_GOLDEN=1"
        );
    }
}
