//! The fine-grained TCB: one **sound** [`Rule<CoreLang>`] ZST per HOL inference
//! step, generated by the [`core_rules!`] catalogue macro.
//!
//! Each rule's `decide` reads its premises' propositions through the public
//! `pure::Thm::prop()` accessor, checks the rule's side conditions, and **derives**
//! the conclusion (it never accepts a caller-supplied conclusion). Every rule is
//! therefore *sound on all inputs*, so admitting its `TypeId` is exactly what
//! confers soundness — this is the admits-only milestone (see `lang.rs`).
//!
//! The macro emits, per rule and from a SINGLE source list:
//! - the ZST,
//! - a typed `prove` fn (the old `Thm` method's term-building + side-condition
//!   logic, moved verbatim),
//! - the [`Rule<CoreLang>`] impl (`decide = prove(..).map_err(to_pure)`),
//! - its [`RuleRecord`] in [`CORE_MANIFEST`], and
//! - its [`core_admits`] arm,
//!
//! so `admits()` and the static manifest can never drift.
//!
//! The public `Thm` methods in `thm/mod.rs` / `thm/typedef.rs` are thin glue: they
//! pull the inner `pure::Thm`s out of the premise `core::Thm`s, call
//! [`covalence_pure::apply`] on the hot path, and — only on the cold failure path —
//! re-run `Rule::prove` to recover the typed [`Error`] for the existing tests.

use std::any::TypeId;
use std::fmt;

use smol_str::SmolStr;

use covalence_pure::{
    App, CanonRule as _, Eqn, Error as PureError, LangMeta, Language, Manifest, Rule, RuleMeta,
    RuleRecord, Val,
};
use covalence_types::Nat;

use crate::ctx::Ctx;
use crate::error::{Error, Result};
use crate::hol;
use crate::subst::{
    close_var, collect_term_tvars, has_free_var_typed, open, shift_by, subst_free,
    subst_tfree_in_term, uses_bound_outer,
};
use crate::term::{Def, FreshId, Term, TermKind, Type, TypeKind, Var};
use crate::tohol::{HolApp, NatAddEqE, ToHolNat, ToHolNatE, nat_add_eq_expr};
use crate::ty::{TypeList, TypeSpec};

use super::lang::{CoreLang, CoreProp, IsThm};

/// An unforgeable premise: a `pure::Thm` carrying an `IsThm`-headed proposition,
/// only mintable via an admitted rule (see `lang.rs`).
pub(crate) type Prem = covalence_pure::Thm<CoreLang, CoreProp>;

/// Read a premise's sequent `(Γ, φ)` by reference (reading never mints).
pub(crate) fn parts(p: &Prem) -> (&Ctx, &Term) {
    let q = p.prop();
    (&q.1.0.0, &q.1.1.0)
}

/// The soundness floor (the old `Thm::build` body): the conclusion and every
/// hypothesis must be well-typed at kind `bool`, then wrap into the `IsThm`
/// proposition. Every rule bottoms out here.
fn seq(hyps: Ctx, concl: Term) -> Result<CoreProp> {
    let ty = concl.type_of()?;
    if !ty.is_bool() {
        return Err(Error::NotBool(ty));
    }
    for h in &hyps {
        let hty = h.type_of()?;
        if !hty.is_bool() {
            return Err(Error::NotBool(hty));
        }
    }
    Ok(App(IsThm, (Val(hyps), Val(concl))))
}

/// Lower a typed [`Error`] into pure's stringly-typed `RuleFailed`. Only used on
/// `decide`'s error path; the public glue recovers the typed error separately.
fn to_pure(e: Error) -> PureError {
    PureError::RuleFailed(e.to_string())
}

/// One rule ⇒ ZST + typed `prove` + `Rule` impl + admits arm + `RuleRecord`, all
/// in lockstep from one source list, so `admits()`/`MANIFEST` cannot drift.
///
/// Three sections, all feeding the SAME manifest/admits emission:
/// - `rules { … }` — the sequent rules: `Concl = CoreProp`, minted through the
///   `seq` well-typedness floor; `Rule<CoreLang>` only.
/// - `raw { … }` — the toHOL tier: rules whose `Concl` is an arbitrary
///   `Expr<Ty = bool>` (symbolic-term equations / certificates), implemented
///   `Rule<L>` for **every** `L: Language` (the gate is still `admits` on the
///   rule's own `TypeId`, so a language admits it only by enumerating it —
///   this is what lets the NotAdmitted negative test run under `()`).
/// - `canon { … }` — [`covalence_pure::CanonRule`] ops admitted for
///   [`covalence_pure::canon`] evaluation (no `Rule` impl; the op's own
///   `TypeId` is the gate identity).
macro_rules! core_rules {
    (
        rules { $( $(#[$d:meta])* $N:ident($($ty:ty),* $(,)?) = |$p:pat_param, $l:pat_param| $b:block )+ }
        raw { $( $(#[$rd:meta])* $R:ident($rin:ty) -> $rc:ty = |$rp:pat_param, $rl:pat_param| $rb:block )+ }
        canon { $( $K:ident ),+ $(,)? }
    ) => {
        $(
            $(#[$d])*
            #[derive(Clone, Copy)]
            pub(crate) struct $N;

            impl $N {
                // The inner closure is load-bearing: rule bodies use early
                // `return Err(..)`, which must exit to the closure's
                // `Result<(Ctx, Term)>` (distinct from `prove`'s `Result<CoreProp>`,
                // which `seq` bridges) — so this is NOT a redundant closure call.
                #[allow(clippy::redundant_closure_call)]
                pub(crate) fn prove($p: ($($ty,)*), $l: &CoreLang) -> Result<CoreProp> {
                    let (hyps, concl) = (|| -> Result<(Ctx, Term)> { $b })()?;
                    seq(hyps, concl)
                }
            }

            impl Rule<CoreLang> for $N {
                type Input = ($($ty,)*);
                type Concl = CoreProp;
                fn decide(
                    self,
                    input: Self::Input,
                    lang: &CoreLang,
                ) -> core::result::Result<CoreProp, PureError> {
                    Self::prove(input, lang).map_err(to_pure)
                }
            }
        )+

        $(
            $(#[$rd])*
            #[derive(Clone, Copy)]
            pub struct $R;

            impl<L: Language> Rule<L> for $R {
                type Input = $rin;
                type Concl = $rc;
                fn decide(
                    self,
                    input: Self::Input,
                    lang: &L,
                ) -> core::result::Result<$rc, PureError> {
                    let ($rp, $rl) = (input, lang);
                    $rb
                }
            }
        )+

        /// The static TCB manifest for [`CoreLang`] — one [`RuleRecord`] per
        /// admitted rule (sequent, raw, and canon sections alike), emitted from
        /// the same source lists as [`core_admits`]. The single parent is the
        /// [`covalence_pure_eval::Builtins`] manifest (embedded by value), so
        /// `tree(CoreLang)` — core's rules plus the enumerable native
        /// computation — is readable from this one static.
        pub(crate) static CORE_MANIFEST: Manifest = Manifest {
            ty: TypeId::of::<CoreLang>(),
            extends: &[covalence_pure_eval::BUILTINS_MANIFEST],
            admits: &[
                $( RuleRecord { ty: TypeId::of::<$N>(), metadata: RuleMeta }, )+
                $( RuleRecord { ty: TypeId::of::<$R>(), metadata: RuleMeta }, )+
                $( RuleRecord { ty: TypeId::of::<$K>(), metadata: RuleMeta }, )+
            ],
            metadata: LangMeta,
        };

        /// The admits predicate for [`CoreLang`], emitted from the same lists as
        /// [`CORE_MANIFEST`]: `true` exactly for the admitted rule TypeIds.
        pub(crate) fn core_admits(r: TypeId) -> bool {
            $( r == TypeId::of::<$N>() )||+
            $( || r == TypeId::of::<$R>() )+
            $( || r == TypeId::of::<$K>() )+
        }

        /// Untrusted name projection of [`CORE_MANIFEST`] (same order, 1:1) —
        /// the source-level rule idents, for the `docs/deps/core-manifest.txt`
        /// golden. Identity is always the `TypeId`.
        #[cfg(test)]
        pub(crate) fn core_rule_names() -> Vec<(&'static str, TypeId)> {
            vec![
                $( (stringify!($N), TypeId::of::<$N>()), )+
                $( (stringify!($R), TypeId::of::<$R>()), )+
                $( (stringify!($K), TypeId::of::<$K>()), )+
            ]
        }
    };
}

/// Public-method glue: apply on the hot path, recover the typed [`Error`] cold.
///
/// `$apply_input` is built from `Arc`-clones (moved into `apply`); `$prove_input`
/// reuses the originals for the cold re-run of `prove`. `decide == prove.map_err`,
/// so `apply` fails iff `prove` fails on the same input ⇒ the cold `unwrap_err`
/// never panics on a real rule failure.
macro_rules! mint {
    ($R:ident, $apply_input:expr, $prove_input:expr) => {
        match covalence_pure::apply(crate::thm::lang::CoreLang, $R, $apply_input) {
            Ok(inner) => Ok(crate::thm::Thm(inner)),
            Err(_) => Err($R::prove($prove_input, &crate::thm::lang::CoreLang).unwrap_err()),
        }
    };
}

pub(crate) use mint;

core_rules! {
    rules {
    // ================= Group A: equality + congruence =================

    /// `⊢ t = t`.
    Refl(Term) = |(t,), _| {
        let _ = t.type_of()?;
        Ok((Ctx::new(), hol::hol_eq(t.clone(), t)))
    }

    /// `Γ ⊢ b = a`, given `Γ ⊢ a = b`.
    Sym(Prem) = |(t,), _| {
        let (hyps, concl) = parts(&t);
        let (a, b, alpha) = super::parse_hol_eq_at(concl)?;
        Ok((hyps.clone(), hol::hol_eq_at(alpha.clone(), b.clone(), a.clone())))
    }

    /// `Γ ∪ Δ ⊢ s = u`, given `Γ ⊢ s = t` and `Δ ⊢ t = u`.
    Trans(Prem, Prem) = |(a, b), _| {
        let (ha, ca) = parts(&a);
        let (hb, cb) = parts(&b);
        let (s, t1, alpha) = super::parse_hol_eq_at(ca)?;
        let (t2, u) = super::parse_hol_eq(cb)?;
        if t1 != t2 {
            return Err(Error::TransMiddleMismatch {
                left: format!("{}", t1),
                right: format!("{}", t2),
            });
        }
        Ok((ha.union(hb), hol::hol_eq_at(alpha.clone(), s.clone(), u.clone())))
    }

    /// `Γ ∪ Δ ⊢ f x = g y`, given `Γ ⊢ f = g` and `Δ ⊢ x = y`.
    MkComb(Prem, Prem) = |(f_thm, arg), _| {
        let (hf, cf) = parts(&f_thm);
        let (hx, cx) = parts(&arg);
        let (f, g, funty) = super::parse_hol_eq_at(cf)?;
        let (x, y) = super::parse_hol_eq(cx)?;
        let TypeKind::Fun(_dom, cod) = funty.kind() else {
            return Err(Error::NotFunction(funty.clone()));
        };
        let cod = cod.clone();
        let lhs = Term::app(f.clone(), x.clone());
        let rhs = Term::app(g.clone(), y.clone());
        Ok((hf.union(hx), hol::hol_eq_at(cod, lhs, rhs)))
    }

    /// `Γ ⊢ (λx:τ. s[x]) = (λx:τ. t[x])`, given `Γ ⊢ s = t` with `(name:τ)` not
    /// free in `Γ`.
    Abs(Prem, SmolStr, Type) = |(t, name, ty), _| {
        let (hyps, concl) = parts(&t);
        let (s, body_t, alpha) = super::parse_hol_eq_at(concl)?;
        let alpha = alpha.clone();
        let var = Var::new(name.as_str(), ty.clone());
        for h in hyps.iter() {
            if has_free_var_typed(h, &var) {
                return Err(Error::FreeVarInHyps { name: name.clone() });
            }
        }
        let s = s.clone();
        let body_t = body_t.clone();
        let s_abs = Term::abs(ty.clone(), close_var(&s, &var));
        let t_abs = Term::abs(ty.clone(), close_var(&body_t, &var));
        Ok((hyps.clone(), hol::hol_eq_at(Type::fun(ty, alpha), s_abs, t_abs)))
    }

    /// `⊢ (λx:τ. body) arg = body[arg/0]` — one outermost β-step.
    BetaConv(Term) = |(app,), _| {
        let TermKind::App(fun, arg) = app.kind() else {
            return Err(Error::NotApp(format!("{}", app)));
        };
        let TermKind::Abs(ty, body) = fun.kind() else {
            return Err(Error::NotAbs(format!("{}", fun)));
        };
        let arg_ty = arg.type_of()?;
        if arg_ty != *ty {
            return Err(Error::TypeMismatch { expected: ty.clone(), got: arg_ty });
        }
        let rhs = open(body, arg);
        Ok((Ctx::new(), hol::hol_eq(app.clone(), rhs)))
    }

    /// `⊢ (λx:τ. f x) = f`, when `Bound(0)` does not appear free in `f`.
    EtaConv(Term) = |(abs,), _| {
        let TermKind::Abs(ty, body) = abs.kind() else {
            return Err(Error::NotAbs(format!("{}", abs)));
        };
        let TermKind::App(f, x) = body.kind() else {
            return Err(Error::EtaShape);
        };
        let TermKind::Bound(0) = x.kind() else {
            return Err(Error::EtaShape);
        };
        if uses_bound_outer(f, 0) {
            return Err(Error::EtaShape);
        }
        let _ = abs.type_of()?;
        let _ = ty;
        let f_outer = shift_by(f, -1, 0);
        Ok((Ctx::new(), hol::hol_eq(abs.clone(), f_outer)))
    }

    // ================= Group B: LF / imp / quantifiers =================

    /// `{p} ⊢ p` for `p : bool`.
    Assume(Term) = |(p,), _| {
        let ty = p.type_of()?;
        if !ty.is_bool() {
            return Err(Error::NotBool(ty));
        }
        Ok((Ctx::singleton(p.clone()), p))
    }

    /// `Γ ∪ Δ ⊢ q`, given `Γ ⊢ p = q : bool` and `Δ ⊢ p`.
    EqMp(Prem, Prem) = |(eq_thm, p_thm), _| {
        let (heq, ceq) = parts(&eq_thm);
        let (hp, cp) = parts(&p_thm);
        let (p, q, alpha) = super::parse_hol_eq_at(ceq)?;
        if !alpha.is_bool() {
            return Err(Error::NotBool(alpha.clone()));
        }
        if *p != *cp {
            return Err(Error::ImpAntecedentMismatch {
                expected: format!("{}", p),
                got: format!("{}", cp),
            });
        }
        Ok((heq.union(hp), q.clone()))
    }

    /// `(Γ \ {q}) ∪ (Δ \ {p}) ⊢ p ⇔ q`, given `Γ ⊢ p` and `Δ ⊢ q` (both bool).
    DeductAntisym(Prem, Prem) = |(a, b), _| {
        let (ha, ca) = parts(&a);
        let (hb, cb) = parts(&b);
        let p_ty = ca.type_of()?;
        let q_ty = cb.type_of()?;
        if !p_ty.is_bool() {
            return Err(Error::NotBool(p_ty));
        }
        if !q_ty.is_bool() {
            return Err(Error::NotBool(q_ty));
        }
        let p = ca.clone();
        let q = cb.clone();
        let hyps_p_minus_q = ha.remove(&q);
        let hyps_q_minus_p = hb.remove(&p);
        Ok((hyps_p_minus_q.union(&hyps_q_minus_p), hol::hol_eq(p, q)))
    }

    /// `Γ \ {φ} ⊢ φ ⟹ ψ`, given `Γ ⊢ ψ` (`φ : bool`).
    ImpIntro(Prem, Term) = |(t, phi), _| {
        let (hyps, concl) = parts(&t);
        let phi_ty = phi.type_of()?;
        if !phi_ty.is_bool() {
            return Err(Error::NotBool(phi_ty));
        }
        let hyps2 = hyps.remove(&phi);
        Ok((hyps2, hol::hol_imp(phi.clone(), concl.clone())))
    }

    /// `Γ ∪ Δ ⊢ ψ`, given `Γ ⊢ φ ⟹ ψ` and `Δ ⊢ φ`.
    ImpElim(Prem, Prem) = |(imp, hyp), _| {
        let (himp, cimp) = parts(&imp);
        let (hh, ch) = parts(&hyp);
        let (phi, psi) = super::parse_hol_imp(cimp)?;
        if *phi != *ch {
            return Err(Error::ImpAntecedentMismatch {
                expected: format!("{}", phi),
                got: format!("{}", ch),
            });
        }
        Ok((himp.union(hh), psi.clone()))
    }

    /// `Γ ⊢ ∀x:τ. φ`, given `Γ ⊢ φ` with `(name:τ)` not free in `Γ`.
    AllIntro(Prem, SmolStr, Type) = |(t, name, ty), _| {
        let (hyps, concl) = parts(&t);
        let var = Var::new(name.as_str(), ty.clone());
        for h in hyps.iter() {
            if has_free_var_typed(h, &var) {
                return Err(Error::FreeVarInHyps { name: name.clone() });
            }
        }
        Ok((hyps.clone(), hol::hol_forall(name.as_str(), ty, concl.clone())))
    }

    /// `Γ ⊢ φ[t/x]`, given `Γ ⊢ ∀x:τ. φ` and `t : τ`.
    AllElim(Prem, Term) = |(t, witness), _| {
        let (hyps, concl) = parts(&t);
        let (ty, body) = super::parse_hol_forall(concl)?;
        let wit_ty = witness.type_of()?;
        if wit_ty != *ty {
            return Err(Error::TypeMismatch { expected: ty.clone(), got: wit_ty });
        }
        let opened = open(body, &witness);
        Ok((hyps.clone(), opened))
    }

    // ================= Group C: connectives =================

    /// `Γ ∪ Δ ⊢ p ∧ q`, given `Γ ⊢ p` and `Δ ⊢ q`.
    AndIntro(Prem, Prem) = |(a, b), _| {
        let (ha, ca) = parts(&a);
        let (hb, cb) = parts(&b);
        let p_ty = ca.type_of()?;
        if !p_ty.is_bool() {
            return Err(Error::NotBool(p_ty));
        }
        let q_ty = cb.type_of()?;
        if !q_ty.is_bool() {
            return Err(Error::NotBool(q_ty));
        }
        Ok((ha.union(hb), hol::hol_and(ca.clone(), cb.clone())))
    }

    /// `Γ ⊢ p`, given `Γ ⊢ p ∧ q`.
    AndElimL(Prem) = |(t,), _| {
        let (hyps, concl) = parts(&t);
        let (p, _q) = super::parse_hol_and(concl)?;
        Ok((hyps.clone(), p.clone()))
    }

    /// `Γ ⊢ q`, given `Γ ⊢ p ∧ q`.
    AndElimR(Prem) = |(t,), _| {
        let (hyps, concl) = parts(&t);
        let (_p, q) = super::parse_hol_and(concl)?;
        Ok((hyps.clone(), q.clone()))
    }

    /// `Γ ⊢ p ∨ q`, given `Γ ⊢ p` and `q : bool`.
    OrIntroL(Prem, Term) = |(t, q), _| {
        let (hyps, concl) = parts(&t);
        let p_ty = concl.type_of()?;
        if !p_ty.is_bool() {
            return Err(Error::NotBool(p_ty));
        }
        let q_ty = q.type_of()?;
        if !q_ty.is_bool() {
            return Err(Error::NotBool(q_ty));
        }
        Ok((hyps.clone(), hol::hol_or(concl.clone(), q)))
    }

    /// `Γ ⊢ p ∨ q`, given `Γ ⊢ q` and `p : bool`.
    OrIntroR(Prem, Term) = |(t, p), _| {
        let (hyps, concl) = parts(&t);
        let q_ty = concl.type_of()?;
        if !q_ty.is_bool() {
            return Err(Error::NotBool(q_ty));
        }
        let p_ty = p.type_of()?;
        if !p_ty.is_bool() {
            return Err(Error::NotBool(p_ty));
        }
        Ok((hyps.clone(), hol::hol_or(p, concl.clone())))
    }

    /// `Γ ∪ Δ₁ ∪ Δ₂ ⊢ r`, given `Γ ⊢ p ∨ q`, `Δ₁ ⊢ p ⟹ r`, `Δ₂ ⊢ q ⟹ r`.
    OrElim(Prem, Prem, Prem) = |(disj, left, right), _| {
        let (hd, cd) = parts(&disj);
        let (hl, cl) = parts(&left);
        let (hr, cr) = parts(&right);
        let (p, q) = super::parse_hol_or(cd)?;
        let (lp, lr) = super::parse_hol_imp(cl)?;
        let (rq, rr) = super::parse_hol_imp(cr)?;
        if lp != p {
            return Err(Error::ConnectiveRule(format!(
                "or_elim: left branch antecedent {lp} ≠ left disjunct {p}"
            )));
        }
        if rq != q {
            return Err(Error::ConnectiveRule(format!(
                "or_elim: right branch antecedent {rq} ≠ right disjunct {q}"
            )));
        }
        if lr != rr {
            return Err(Error::ConnectiveRule(format!(
                "or_elim: branch consequents differ ({lr} vs {rr})"
            )));
        }
        Ok((hd.union(hl).union(hr), lr.clone()))
    }

    /// `Γ ⊢ ¬p`, given `Γ ⊢ p ⟹ F`.
    NotIntro(Prem) = |(t,), _| {
        let (hyps, concl) = parts(&t);
        let (p, f) = super::parse_hol_imp(concl)?;
        if !matches!(f.kind(), TermKind::Bool(false)) {
            return Err(Error::ConnectiveRule(format!(
                "not_intro: consequent {f} is not F"
            )));
        }
        Ok((hyps.clone(), hol::hol_not(p.clone())))
    }

    /// `Γ ∪ Δ ⊢ F`, given `Γ ⊢ ¬p` and `Δ ⊢ p`.
    NotElim(Prem, Prem) = |(neg, other), _| {
        let (hn, cn) = parts(&neg);
        let (ho, co) = parts(&other);
        let p = super::parse_hol_not(cn)?;
        if *p != *co {
            return Err(Error::ConnectiveRule(format!(
                "not_elim: negated {p} ≠ hypothesis {}",
                co
            )));
        }
        Ok((hn.union(ho), Term::bool_lit(false)))
    }

    // ================= Group D: substitution =================

    /// `Γ[x:=r] ⊢ φ[x:=r]` — substitute free `(name, r.type)` by `r`.
    Inst(Prem, SmolStr, Term) = |(t, name, replacement), _| {
        let (hyps, concl) = parts(&t);
        let var = Var::new(name.as_str(), replacement.type_of()?);
        let new_concl = subst_free(concl, &var, &replacement);
        let new_hyps = hyps.map(|h| subst_free(h, &var, &replacement));
        Ok((new_hyps, new_concl))
    }

    /// `Γ[α:=σ] ⊢ φ[α:=σ]`.
    InstTFree(Prem, SmolStr, Type) = |(t, name, replacement), _| {
        let (hyps, concl) = parts(&t);
        let new_concl = subst_tfree_in_term(concl, name.as_str(), &replacement);
        let new_hyps = hyps.map(|h| subst_tfree_in_term(h, name.as_str(), &replacement));
        Ok((new_hyps, new_concl))
    }

    // ================= Group E: structural =================

    /// `Δ ⊢ φ`, given `Γ ⊢ φ` and `Γ ⊆ Δ`.
    Weaken(Prem, Ctx) = |(t, target), _| {
        let (hyps, concl) = parts(&t);
        if !hyps.is_subset(&target) {
            return Err(Error::NotASuperset);
        }
        Ok((target, concl.clone()))
    }

    // ================= Group F: TypeSpec abs/rep laws =================

    /// `⊢ abs (rep a) = a`.
    SpecAbsRep(TypeSpec, TypeList, Term) = |(spec, args, a), _| {
        let (abs, rep, _carrier, wrapper) = super::spec_coercions(&spec, &args)?;
        let a_ty = a.type_of()?;
        if a_ty != wrapper {
            return Err(Error::TypeMismatch { expected: wrapper, got: a_ty });
        }
        let lhs = Term::app(abs, Term::app(rep, a.clone()));
        Ok((Ctx::new(), hol::hol_eq(lhs, a)))
    }

    /// `⊢ P a ⟹ rep (abs a) = a`.
    SpecRepAbsFwd(TypeSpec, TypeList, Term) = |(spec, args, a), _| {
        let (abs, rep, carrier, _wrapper) = super::spec_coercions(&spec, &args)?;
        let a_ty = a.type_of()?;
        if a_ty != carrier {
            return Err(Error::TypeMismatch { expected: carrier, got: a_ty });
        }
        let pred = super::subtype_pred(&spec, &args, &carrier)?;
        let prem = Term::app(pred, a.clone());
        let eq = hol::hol_eq(Term::app(rep, Term::app(abs, a.clone())), a);
        Ok((Ctx::new(), hol::hol_imp(prem, eq)))
    }

    /// `⊢ rep (abs a) = a ⟹ (P a ∨ ¬∃x. P x)`.
    SpecRepAbsBack(TypeSpec, TypeList, Term) = |(spec, args, a), _| {
        let (abs, rep, carrier, _wrapper) = super::spec_coercions(&spec, &args)?;
        let a_ty = a.type_of()?;
        if a_ty != carrier {
            return Err(Error::TypeMismatch { expected: carrier, got: a_ty });
        }
        let pred = super::subtype_pred(&spec, &args, &carrier)?;
        let prem = hol::hol_eq(Term::app(rep, Term::app(abs, a.clone())), a.clone());
        let pa = Term::app(pred.clone(), a);
        let some_x = hol::hol_exists(
            "x",
            carrier.clone(),
            Term::app(pred, Term::free("x", carrier)),
        );
        let disj = hol::hol_or(pa, hol::hol_not(some_x));
        Ok((Ctx::new(), hol::hol_imp(prem, disj)))
    }

    /// `⊢ (p w) ⟹ p(t)` for a def-style `TermSpec` leaf `t` with witness `w`.
    SpecAx(Term, Term) = |(t, w), _| {
        let (spec, args) = match t.kind() {
            TermKind::Spec(spec, args) => (spec.clone(), args.clone()),
            _ => return Err(Error::NotASpec),
        };
        let declared_ty = spec.ty().ok_or(Error::SpecHasNoBody)?.clone();
        let body = spec.tm().ok_or(Error::SpecHasNoBody)?.clone();
        let body_ty = body.type_of()?;
        if body_ty != Type::fun(declared_ty.clone(), Type::bool()) {
            return Err(Error::SpecIsLetStyle);
        }
        let tvars = declared_ty.free_tvars();
        let pred = super::inst_spec_tvars(&body, &tvars, &args);
        let carrier = t.type_of()?;
        let w_ty = w.type_of()?;
        if w_ty != carrier {
            return Err(Error::TypeMismatch { expected: carrier, got: w_ty });
        }
        let prem = Term::app(pred.clone(), w);
        let concl = Term::app(pred, t.clone());
        Ok((Ctx::new(), hol::hol_imp(prem, concl)))
    }

    // ================= Group A': computational (builtins in-TCB) =================

    /// `⊢ Spec(spec, args) = subst(spec.tm, tvars, args)` for a let-style spec.
    UnfoldTermSpec(Term) = |(t,), _| {
        let (spec, args) = match t.kind() {
            TermKind::Spec(spec, args) => (spec.clone(), args.clone()),
            _ => return Err(Error::NotASpec),
        };
        let declared_ty = spec.ty().ok_or(Error::SpecHasNoBody)?.clone();
        let body = spec.tm().ok_or(Error::SpecHasNoBody)?.clone();
        let body_ty = body.type_of()?;
        if body_ty != declared_ty {
            return Err(Error::SpecIsDefStyle);
        }
        let tvars = declared_ty.free_tvars();
        let unfolded = super::inst_spec_tvars(&body, &tvars, &args);
        Ok((Ctx::new(), hol::hol_eq(t, unfolded)))
    }

    /// `⊢ t = result` — single-step closed-form literal computation.
    ReducePrim(Term) = |(t,), _| {
        // Type-check `t` first: `reduce_prim_term` matches purely on shape and
        // would "reduce" an ill-typed application, which `hol_eq` would then
        // reject on a bad type. Validating here turns that into a clean `Err`.
        let _ = t.type_of()?;
        let reduced = crate::builtins::reduce_prim_term(&t).ok_or(Error::NotReducible)?;
        Ok((Ctx::new(), hol::hol_eq(t, reduced)))
    }

    // ================= Group G: kernel primitive axioms =================

    /// `⊢ a = b` for `a, b : unit` (the singleton rule).
    UnitEq(Term, Term) = |(a, b), _| {
        let a_ty = a.type_of()?;
        if a_ty != Type::unit() {
            return Err(Error::TypeMismatch { expected: Type::unit(), got: a_ty });
        }
        let b_ty = b.type_of()?;
        if b_ty != Type::unit() {
            return Err(Error::TypeMismatch { expected: Type::unit(), got: b_ty });
        }
        Ok((Ctx::new(), hol::hol_eq(a, b)))
    }

    /// `⊢ (succ m = succ n) ⟹ (m = n)` — successor injectivity (`m, n : nat`).
    SuccInj(Term, Term) = |(m, n), _| {
        let nat = Type::nat();
        for t in [&m, &n] {
            let ty = t.type_of()?;
            if ty != nat {
                return Err(Error::TypeMismatch { expected: nat.clone(), got: ty });
            }
        }
        let prem = hol::hol_eq(
            Term::app(Term::succ(), m.clone()),
            Term::app(Term::succ(), n.clone()),
        );
        Ok((Ctx::new(), hol::hol_imp(prem, hol::hol_eq(m, n))))
    }

    /// `⊢ ¬(0 = succ n)` (`n : nat`).
    ZeroNeSucc(Term) = |(n,), _| {
        let nat = Type::nat();
        let n_ty = n.type_of()?;
        if n_ty != nat {
            return Err(Error::TypeMismatch { expected: nat, got: n_ty });
        }
        let zero = Term::nat_lit(covalence_types::Nat::zero());
        let eq = hol::hol_eq(zero, Term::app(Term::succ(), n));
        Ok((Ctx::new(), hol::hol_not(eq)))
    }

    /// `Γ ⊢ p`, given `Γ ⊢ F` and `p : bool` (ex falso).
    FalseElim(Prem, Term) = |(t, p), _| {
        let (hyps, concl) = parts(&t);
        if !matches!(concl.kind(), TermKind::Bool(false)) {
            return Err(Error::ConnectiveRule(format!(
                "false_elim: conclusion {} is not F",
                concl
            )));
        }
        let p_ty = p.type_of()?;
        if !p_ty.is_bool() {
            return Err(Error::NotBool(p_ty));
        }
        Ok((hyps.clone(), p))
    }

    /// `Γ₁ ∪ Γ₂ ⊢ ∀n:nat. p n`, given `Γ₁ ⊢ p 0` and `Γ₂ ⊢ p n ⟹ p (succ n)`
    /// with the GEN side conditions on `n`.
    NatInduct(Prem, Prem) = |(base, step), _| {
        let nat = Type::nat();
        let zero = Term::nat_lit(covalence_types::Nat::zero());
        let (base_h, base_c) = parts(&base);
        let (step_h, step_c) = parts(&step);

        // base : ⊢ p 0
        let TermKind::App(p, base_arg) = base_c.kind() else {
            return Err(Error::ConnectiveRule(format!(
                "nat_induct: base conclusion {} is not `p 0`",
                base_c
            )));
        };
        if base_arg != &zero {
            return Err(Error::ConnectiveRule(format!(
                "nat_induct: base conclusion {} is not the motive applied to 0",
                base_c
            )));
        }
        let p = p.clone();

        // step : ⊢ p n ⟹ p (succ n)
        let (ante, conseq) = super::parse_hol_imp(step_c)?;
        let TermKind::App(ante_p, n_free) = ante.kind() else {
            return Err(Error::ConnectiveRule(format!(
                "nat_induct: step antecedent {ante} is not `p n`"
            )));
        };
        if *ante_p != p {
            return Err(Error::ConnectiveRule(
                "nat_induct: step uses a different motive than the base".into(),
            ));
        }
        let TermKind::Free(nv) = n_free.kind() else {
            return Err(Error::ConnectiveRule(format!(
                "nat_induct: induction variable {n_free} is not a free variable"
            )));
        };
        if *nv.ty() != nat {
            return Err(Error::ConnectiveRule(format!(
                "nat_induct: induction variable {n_free} is not of type nat"
            )));
        }
        let expected_conseq = Term::app(p.clone(), Term::app(hol::succ_fn(), n_free.clone()));
        if *conseq != expected_conseq {
            return Err(Error::ConnectiveRule(format!(
                "nat_induct: step consequent {conseq} is not `p (succ n)`"
            )));
        }

        // GEN side conditions.
        if has_free_var_typed(&p, nv) {
            return Err(Error::ConnectiveRule(
                "nat_induct: induction variable occurs free in the motive".into(),
            ));
        }
        for h in step_h.iter() {
            if has_free_var_typed(h, nv) {
                return Err(Error::FreeVarInHyps { name: nv.name().into() });
            }
        }

        let n_name = nv.name().to_string();
        let body = Term::app(p, n_free.clone());
        let concl = hol::hol_forall(&n_name, nat, body);
        Ok((base_h.union(step_h), concl))
    }

    // ================= Group G': flagged postulates =================

    /// `⊢ p ∨ ¬p` — the law of excluded middle (classicality axiom).
    Lem(Term) = |(p,), _| {
        let p_ty = p.type_of()?;
        if !p_ty.is_bool() {
            return Err(Error::NotBool(p_ty));
        }
        Ok((Ctx::new(), hol::hol_or(p.clone(), hol::hol_not(p))))
    }

    /// `⊢ (p x) ⟹ (p (ε p))` — Hilbert's choice axiom.
    SelectAx(Term, Term) = |(p, x), _| {
        let p_ty = p.type_of()?;
        let TypeKind::Fun(dom, cod) = p_ty.kind() else {
            return Err(Error::NotFunction(p_ty));
        };
        if !cod.is_bool() {
            return Err(Error::NotBool(cod.clone()));
        }
        let x_ty = x.type_of()?;
        if *dom != x_ty {
            return Err(Error::TypeMismatch { expected: dom.clone(), got: x_ty });
        }
        let choice = Term::app(Term::select_op(dom.clone()), p.clone());
        let prem = Term::app(p.clone(), x);
        let concl = Term::app(p, choice);
        Ok((Ctx::new(), hol::hol_imp(prem, concl)))
    }

    // ================= Group I: generative (fresh identity INSIDE decide) =================

    /// `⊢ Def(name, body) ≡ body` with a FRESH `Def` allocated here — never a
    /// caller-supplied `Def`, so no collision can forge `body₁ ≡ body₂`.
    Define(SmolStr, Term) = |(name, body), _| {
        let body_type = body.type_of()?;
        // No "phantom" tvars (Isabelle/Pure parity): every free tvar inside
        // `body`'s type annotations must appear in `body_type`.
        let type_tvars: std::collections::BTreeSet<SmolStr> =
            body_type.free_tvars().into_iter().collect();
        let mut body_tvars = std::collections::BTreeSet::new();
        collect_term_tvars(&body, &mut body_tvars);
        for tv in &body_tvars {
            if !type_tvars.contains(tv) {
                return Err(Error::DefPhantomTFree {
                    tvar: tv.clone(),
                    body_type,
                });
            }
        }
        let d = Def::new_internal(name, body.clone(), body_type);
        Ok((Ctx::new(), hol::hol_eq(Term::def(d), body)))
    }

    /// From a witness `Γ ⊢ P x`, mint `Γ ⊢ abs_rep ∧ (fwd ∧ back)` for a FRESH
    /// subtype τ with fresh abs/rep — all freshness allocated here. The public
    /// `new_type_definition` splits the conjunction via core's own `and_elim` and
    /// shape-parses τ/abs/rep back out.
    NewTypeDefRule(Prem, SmolStr, SmolStr) = |(witness, abs_hint, rep_hint), _| {
        let (w_hyps, w_concl) = parts(&witness);

        // 1. Decompose witness concl as `P x`.
        let TermKind::App(p, x) = w_concl.kind() else {
            return Err(Error::BadTypeDefWitness(format!("{}", w_concl)));
        };
        let p = p.clone();
        let x = x.clone();

        // 2-3. α from x; validate P : α → bool.
        let alpha = x.type_of()?;
        let p_ty = p.type_of()?;
        let TypeKind::Fun(p_dom, p_cod) = p_ty.kind() else {
            return Err(Error::NotFunction(p_ty));
        };
        if *p_dom != alpha {
            return Err(Error::TypeMismatch { expected: alpha.clone(), got: p_dom.clone() });
        }
        if !p_cod.is_bool() {
            return Err(Error::NotBool(p_cod.clone()));
        }

        // 4. tvar arity from α.
        let tvar_names = alpha.free_tvars();
        let tvar_types: Vec<Type> = tvar_names.iter().map(|n| Type::tfree(n.clone())).collect();

        // 5-6. Fresh identity (τ, abs, rep) allocated INSIDE decide: three
        //      `FreshId` tokens over the private markers below, so no caller
        //      can supply (or collide) an identity.
        let tau = Type::fresh_tycon(FreshId::new(TypeDefMarker), tvar_types);
        let abs_ty = Type::fun(alpha.clone(), tau.clone());
        let rep_ty = Type::fun(tau.clone(), alpha.clone());
        let abs = Term::fresh_const(FreshId::new(TypeDefAbsMarker { hint: abs_hint }), abs_ty);
        let rep = Term::fresh_const(FreshId::new(TypeDefRepMarker { hint: rep_hint }), rep_ty);

        // 7. The three bijection theorems, combined into one conjunction.
        //    abs_rep: ∀a:τ. abs (rep a) = a
        let a_free = Term::free("a", tau.clone());
        let abs_rep_body = hol::hol_eq(
            Term::app(abs.clone(), Term::app(rep.clone(), a_free.clone())),
            a_free,
        );
        let abs_rep_concl = hol::hol_forall("a", tau.clone(), abs_rep_body);

        let r_free = Term::free("r", alpha.clone());
        let p_at_r = Term::app(p, r_free.clone());
        let rep_abs_eq = hol::hol_eq(
            Term::app(rep.clone(), Term::app(abs.clone(), r_free.clone())),
            r_free,
        );
        //    fwd: ∀r:α. P r ⟹ rep (abs r) = r
        let fwd_concl = hol::hol_forall(
            "r",
            alpha.clone(),
            hol::hol_imp(p_at_r.clone(), rep_abs_eq.clone()),
        );
        //    back: ∀r:α. rep (abs r) = r ⟹ P r
        let back_concl = hol::hol_forall("r", alpha, hol::hol_imp(rep_abs_eq, p_at_r));

        let conj = hol::hol_and(abs_rep_concl, hol::hol_and(fwd_concl, back_concl));
        Ok((w_hyps.clone(), conj))
    }
    }

    // ================= Group H: the toHOL tier (symbolic conclusions) =========
    //
    // These rules' conclusions are NOT `CoreProp`: they are base propositions
    // over symbolic HOL-term expressions (`toHOL` denotations, never-constructed
    // canonical terms). They mint via `covalence_pure::apply` directly — the
    // public `mint!` glue (and its cold-path invariant) does not apply; every
    // `decide` below is deterministic and total on its input.

    raw {
    /// TRANSITIONAL (dies with the kernel `Nat` literals — see `SKELETONS.md`):
    /// `⊢ toHOL n = Val(⌜n⌝)` — reify a `toHOL`-denoted natural to today's
    /// literal-numeral `Term`.
    ///
    /// ## Soundness
    ///
    /// While the kernel `Nat` literals exist, the literal numeral IS the
    /// kernel's canonical HOL term for the natural `n` (the same denotational
    /// commitment the legacy literal reducer documents: literals denote the
    /// standard values). `toHOL n` denotes exactly that term, so the equation
    /// holds by definition of the denotation. At literal-deletion time this
    /// rule is deleted and the permanent structural rules (`toHOL 0 = ⌜zero⌝`,
    /// `toHOL (n+1) = S (toHOL n)`) take over; only the reify target flips.
    ToHolNatVal(Nat) -> Eqn<ToHolNatE, Val<Term>> = |n, _| {
        let t = Term::nat_lit(n.clone());
        Ok(Eqn(App(ToHolNat, Val(n)), Val(t)))
    }

    /// `⊢ (Val f, Val x) = Val((f, x))` at the `(Term, Term)` product sort —
    /// fuse a tuple of ground leaves into one ground tuple leaf. The bridge
    /// between `cong_pair` (which produces tuples **of** `Val`s) and
    /// [`covalence_pure::canon`] (whose evaluated redex takes its whole input
    /// as one `Val` **of** a tuple).
    ///
    /// ## Soundness
    ///
    /// Both sides denote the same pair `(f, x)` of the product sort — tuple
    /// expressions denote tuples of their components' denotations, and `Val`
    /// leaves denote themselves. The two shapes are one value read two ways;
    /// no computation, no new equalities between distinct values.
    PairVal((Term, Term)) -> Eqn<(Val<Term>, Val<Term>), Val<(Term, Term)>> = |(f, x), _| {
        Ok(Eqn((Val(f.clone()), Val(x.clone())), Val((f, x))))
    }

    /// The nat.add computation-backed derivability certificate:
    /// `⊢ IsThm(∅, ⌜nat.add (toHOL a) (toHOL b) = toHOL (a + b)⌝)`, where the
    /// sum is computed natively by the [`covalence_pure_eval::NatAdd`]
    /// [`CanonRule`](covalence_pure::CanonRule) and the HOL equation stays
    /// **symbolic** (its numeral leaves are `toHOL` denotations — never
    /// materialized).
    ///
    /// ## Soundness (the existence-without-construction contract)
    ///
    /// The soundness contract of every such rule (its docstring obligation):
    /// for every native value `b` there *exists* a HOL term `[b]` such that
    /// the defining properties are derivable in pure HOL —
    /// existence-without-construction, the same principle as "a standard
    /// theorem means a derivation exists". Concretely here: `[n]` is the
    /// numeral `S^n(Z)`, and whenever the native addition computes
    /// `a + b = c`, the HOL equation `nat.add [a] [b] = [c]` is derivable in
    /// pure HOL by `c` primitive-recursive unfoldings of `nat.add`'s
    /// definitional equations on the numerals — the derivation exists for
    /// every `(a, b)`, and this rule is a certified shortcut that never adds
    /// strength. The rule derives its whole conclusion from the input pair
    /// (no caller-supplied conclusion), so it is sound on ALL inputs.
    NatAddCert((Nat, Nat)) -> App<IsThm, (Val<Ctx>, NatAddEqE)> = |(a, b), _| {
        let sum = covalence_pure_eval::NatAdd.eval(&(a.clone(), b.clone()));
        Ok(App(IsThm, (Val(Ctx::new()), nat_add_eq_expr(a, b, sum))))
    }
    }

    // CanonRule ops admitted for `covalence_pure::canon` under `CoreLang`
    // (soundness documented on each op — see `crate::tohol`).
    canon { HolApp }
}

// ============================================================================
// new_type_definition fresh-identity markers (wrapped in `FreshId` tokens
// allocated only inside `NewTypeDefRule::decide`).
// ============================================================================
//
// The freshness itself comes from each `FreshId::new` call (a fresh `Arc`
// per token); the markers below are display-only payloads (`Debug` feeds
// `Term`/`Type` printing). They are private to this module, so even the
// marker *types* cannot be named downstream.

/// Marker inside a fresh subtype's `Type::fresh_tycon` token.
#[derive(Debug)]
struct TypeDefMarker;

/// Marker inside a typedef's `abs` constant token.
struct TypeDefAbsMarker {
    hint: SmolStr,
}

impl fmt::Debug for TypeDefAbsMarker {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.hint.is_empty() {
            write!(f, "abs")
        } else {
            write!(f, "{}", self.hint)
        }
    }
}

/// Marker inside a typedef's `rep` constant token.
struct TypeDefRepMarker {
    hint: SmolStr,
}

impl fmt::Debug for TypeDefRepMarker {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.hint.is_empty() {
            write!(f, "rep")
        } else {
            write!(f, "{}", self.hint)
        }
    }
}

// ============================================================================
// The CORE_MANIFEST golden (TCB budget): docs/deps/core-manifest.txt
// ============================================================================

#[cfg(test)]
mod manifest_tests {
    use std::any::TypeId;
    use std::collections::HashSet;

    use covalence_pure::Language;

    use super::super::lang::CoreLang;
    use super::{CORE_MANIFEST, core_admits, core_rule_names};

    const GOLDEN: &str = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../../../docs/deps/core-manifest.txt"
    );

    /// Pins the name-projected rule inventory of [`CoreLang`] to
    /// `docs/deps/core-manifest.txt` — a PR that grows the admitted-rule TCB
    /// shows it in-diff. Regenerate with:
    /// `COV_REGEN_GOLDEN=1 cargo test -p covalence-core manifest_matches_golden`
    /// The transitional literal-unfolding rule and the permanent structural
    /// (succ-tower) rules pin CONTRADICTORY denotations for `toHOL n` at the
    /// `Term` sort — admitting both makes the base tier inconsistent (audit
    /// wave-1 finding: sym+trans would equate `Val(nat_lit 1)` with
    /// `Val(app(succ, nat_lit 0))`, a false definitional-Eq fact). This guard
    /// fires the moment both appear in the manifest: delete `ToHolNatVal` in
    /// the SAME commit that admits the structural rules.
    #[test]
    fn tohol_unfolding_rules_are_exclusive() {
        let names = core_rule_names();
        let transitional = names.iter().any(|(n, _)| *n == "ToHolNatVal");
        let structural = names
            .iter()
            .any(|(n, _)| n.starts_with("ToHolNatZero") || n.starts_with("ToHolNatSucc"));
        assert!(
            !(transitional && structural),
            "ToHolNatVal (literal denotation) and the structural succ-tower rules \
             must never be admitted together — they pin contradictory `toHOL` \
             denotations (see thm/SKELETONS.md)"
        );
    }

    #[test]
    fn manifest_matches_golden() {
        let names = core_rule_names();

        // Structure: the manifest is CoreLang's own; its single parent is
        // Builtins (the opened core-on-pure seam); the name projection is 1:1
        // and in the same order.
        assert_eq!(CORE_MANIFEST.ty, TypeId::of::<CoreLang>());
        assert_eq!(CORE_MANIFEST.extends.len(), 1, "one parent: Builtins");
        assert_eq!(
            CORE_MANIFEST.extends[0].ty,
            TypeId::of::<covalence_pure_eval::Builtins>()
        );
        assert!(
            CoreLang.extends(TypeId::of::<covalence_pure_eval::Builtins>()),
            "extends() mirrors the manifest parent"
        );
        assert_eq!(names.len(), CORE_MANIFEST.admits.len(), "1:1 projection");
        for ((name, ty), rec) in names.iter().zip(CORE_MANIFEST.admits) {
            assert_eq!(*ty, rec.ty, "name/manifest order drift at {name}");
        }

        // Identity: no duplicates; admits ⟺ manifest.
        let mut tys = HashSet::new();
        for (name, ty) in &names {
            assert!(tys.insert(*ty), "duplicate rule TypeId for {name}");
            assert!(core_admits(*ty), "manifest rule {name} not admitted");
        }
        assert!(!core_admits(TypeId::of::<CoreLang>()));
        assert!(!core_admits(TypeId::of::<covalence_pure_eval::NatAdd>()));

        // The golden.
        let ours: String = names.iter().map(|(n, _)| *n).collect::<Vec<_>>().join("\n") + "\n";
        if std::env::var_os("COV_REGEN_GOLDEN").is_some() {
            std::fs::write(GOLDEN, &ours).expect("write golden");
            return;
        }
        let golden = std::fs::read_to_string(GOLDEN)
            .expect("read docs/deps/core-manifest.txt (regenerate with COV_REGEN_GOLDEN=1)");
        assert_eq!(
            golden, ours,
            "CORE_MANIFEST drifted from docs/deps/core-manifest.txt — audit \
             the diff, then regenerate with COV_REGEN_GOLDEN=1"
        );
    }
}
