"""Type stubs for the covalence native module (PyO3)."""

from typing import Any, Callable, List, Optional, Tuple, Union

class O256:
    """256-bit hash value. Also acts as a BLAKE3 keyed-hash key."""

    @staticmethod
    def from_hex(hex: str) -> "O256": ...
    @staticmethod
    def from_bytes(data: bytes) -> "O256": ...
    @staticmethod
    def blob(data: bytes) -> "O256": ...
    @property
    def hex(self) -> str: ...
    def hash(self, data: bytes) -> "O256": ...
    def hash_file(self, path: str) -> "O256": ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Component:
    """Validated WASM component with cached metadata."""

    @staticmethod
    def from_wat(text: str) -> "Component": ...
    @staticmethod
    def from_bytes(data: bytes) -> "Component": ...
    @property
    def bytes(self) -> bytes: ...
    @property
    def imports(self) -> list[str]: ...
    @property
    def exports(self) -> list[str]: ...
    @property
    def wat(self) -> str: ...
    @property
    def hash(self) -> O256: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class GitObject:
    """Git object hash (SHA-1 or SHA-256)."""

    @property
    def hex(self) -> str: ...
    @property
    def kind(self) -> str: ...
    def to_o256(self) -> O256:
        """Convert to O256 using identity mapping (SHA-256 only).

        Raises ValueError for SHA-1 objects — use a hash_map instead.
        """
        ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class GitStore:
    """Content-addressed git object store (loose objects)."""

    def __init__(self, path: str, algo: str = "sha1") -> None: ...
    @staticmethod
    def from_repo(path: str, algo: str = "sha1") -> "GitStore": ...
    def insert(self, data: bytes) -> GitObject: ...
    def get(self, key: Union[GitObject, str]) -> Optional[bytes]: ...
    def put(self, key: Union[GitObject, str], data: bytes) -> None: ...
    def contains(self, key: Union[GitObject, str]) -> bool: ...
    def __contains__(self, key: Union[GitObject, str]) -> bool: ...
    @property
    def algo(self) -> str: ...
    def __repr__(self) -> str: ...

class Hasher:
    """Hashing strategy that produces O256 values."""

    def hash(self, data: bytes) -> O256: ...
    def hash_file(self, path: str) -> O256: ...

class GitHasher:
    """Git hashing strategy that produces GitObject values."""

    def hash_blob(self, data: bytes) -> GitObject: ...
    def hash_blob_file(self, path: str) -> GitObject: ...
    def hash_tree(self, data: bytes) -> GitObject: ...

class GitRef:
    """One ref discovered during a git clone."""

    name: str
    oid: str
    symref_target: Optional[str]

class GitImport:
    """Sqlite-backed git object store with the SHA1 → O256 mapping that
    `cov cog clone` builds. Use `GitImport.open(path)` to attach to an
    existing store or `GitImport.clone(url, store=path)` to populate one."""

    @staticmethod
    def open(path: Optional[str] = None, algo: str = "sha1") -> "GitImport": ...
    @staticmethod
    def clone(
        url: str,
        store: Optional[str] = None,
        branch: Optional[str] = None,
        depth: Optional[int] = None,
        filter: Optional[str] = None,
        algo: str = "sha1",
    ) -> "GitCloneResult": ...
    @staticmethod
    def classify(url: str) -> str: ...
    count: int
    cov_tree_count: int
    def resolve(self, oid: Union[GitObject, str]) -> O256: ...
    def reverse(self, target: O256) -> Optional[GitObject]: ...
    def store_blob(self, data: bytes) -> GitObject: ...
    def contains(self, oid: Union[GitObject, str]) -> bool: ...
    def __contains__(self, oid: Union[GitObject, str]) -> bool: ...

class GitCloneResult:
    """Result of `GitImport.clone(...)`."""

    store: GitImport
    objects_stored: int
    url: str
    refs: List[GitRef]
    cov_trees_count: int
    def cov_trees(self) -> List[Tuple[str, O256]]: ...

class StoreProtocol:
    """Protocol for Python-backed stores (informational, not enforced at type level)."""

    def get(self, key: O256) -> Optional[bytes]: ...
    def put(self, key: O256, data: bytes) -> None: ...
    def insert(self, data: bytes) -> O256: ...
    def contains(self, key: O256) -> bool: ...
    def __len__(self) -> int: ...

class Store:
    """Content-addressed blob store."""

    def __init__(self, obj: StoreProtocol) -> None: ...
    @staticmethod
    def memory() -> "Store": ...
    @staticmethod
    def sqlite(path: str) -> "Store": ...
    def insert(self, data: bytes) -> O256: ...
    def get(self, key: Union[O256, str]) -> Optional[bytes]: ...
    def put(self, key: Union[O256, str], data: bytes) -> None: ...
    def contains(self, key: Union[O256, str]) -> bool: ...
    def __contains__(self, key: Union[O256, str]) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class TaggedStore:
    """Tagged content-addressed store with git-style object type tags.

    Wraps any Store in a GitPrefixStore, prepending a "{type} {len}\\0"
    header to every stored value.
    """

    def __init__(self, obj: Any) -> None: ...
    @staticmethod
    def git_prefix(store: Store) -> "TaggedStore": ...
    @staticmethod
    def memory() -> "TaggedStore": ...
    def insert(self, data: bytes) -> O256: ...
    def get(self, key: Union[O256, str]) -> Optional[bytes]: ...
    def put(self, key: Union[O256, str], data: bytes) -> None: ...
    def contains(self, key: Union[O256, str]) -> bool: ...
    def __contains__(self, key: Union[O256, str]) -> bool: ...
    def __len__(self) -> int: ...
    def insert_tagged(self, kind: str, data: bytes) -> O256: ...
    def get_repr(self, key: Union[O256, str]) -> Optional[bytes]: ...
    def get_tag(self, key: Union[O256, str]) -> Optional[str]: ...
    def get_repr_with(self, kind: str, key: Union[O256, str]) -> Optional[bytes]: ...
    def get_tag_with(self, kind: str, key: Union[O256, str]) -> Optional[str]: ...
    def __repr__(self) -> str: ...

class ObjectStore:
    """Typed object store for blobs and trees.

    Two modes:
    - git_tagged — all objects use git-style headers. Supports blob, tree, commit, tag.
    - keyed — blobs are untagged (BLAKE3), trees use keyed hash. Only blob and tree.
    """

    @staticmethod
    def git_tagged(store: TaggedStore) -> "ObjectStore": ...
    @staticmethod
    def git_tagged_memory() -> "ObjectStore": ...
    @staticmethod
    def keyed_memory() -> "ObjectStore": ...
    def insert_blob(self, data: bytes) -> O256: ...
    def get_blob(self, key: Union[O256, str]) -> Optional[bytes]: ...
    def contains_blob(self, key: Union[O256, str]) -> bool: ...
    def insert_tree(self, data: bytes) -> O256: ...
    def get_tree(self, key: Union[O256, str]) -> Optional[bytes]: ...
    def contains_tree(self, key: Union[O256, str]) -> bool: ...
    def insert_tree_json(self, entries: list[dict[str, str]]) -> O256: ...
    def get_tree_json(self, key: Union[O256, str]) -> Optional[list[dict[str, str]]]: ...
    def insert_any(self, kind: str, data: bytes) -> O256: ...
    def get_any(self, key: Union[O256, str]) -> Optional[dict[str, object]]: ...
    def __repr__(self) -> str: ...

FieldSpecItem = Union[str, tuple[str, int]]

class RowSchema:
    """Row schema: list of field specs for a table."""

    def __init__(self, fields: list[FieldSpecItem]) -> None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class TableBuilder:
    """Dynamic table builder using a RowSchema."""

    def __init__(self, schema: RowSchema) -> None: ...
    def push_ref(self, key: Union[O256, str]) -> None: ...
    def push_dep(self, key: Union[O256, str]) -> None: ...
    def push_row(self, fields: list[bytes]) -> None: ...
    def build(self) -> bytes: ...
    @staticmethod
    def parse(data: bytes) -> dict[str, object]: ...

class DirectoryBuilder:
    """Directory table builder using the typed Dir schema.

    Mode strings: "blob", "regular", "executable", "symlink", "dir", "submodule".
    ("blob" is an alias for "regular".)
    """

    def __init__(self) -> None: ...
    def push(self, name: Union[str, bytes], mode: str, child: Union[O256, str]) -> None: ...
    def build(self) -> bytes: ...
    @staticmethod
    def parse(data: bytes) -> dict[str, object]: ...

class Backend:
    """Covalence backend: content store + WASM engine on a background thread."""

    def store(self, data: Union[bytes, str, "Component"]) -> O256: ...
    def store_blob(self, data: bytes) -> O256: ...
    def store_str(self, text: str) -> O256: ...
    def get_blob(self, hash: Union[O256, str]) -> Optional[bytes]: ...
    def has_blob(self, hash: Union[O256, str]) -> bool: ...
    def blob_count(self) -> Optional[int]: ...
    def compile_wat(self, wat: str) -> O256: ...
    def decide(self, hash: Union[O256, str, "Component"]) -> dict[str, object]: ...
    def info(self) -> dict[str, str]: ...

class Session:
    """REPL session for evaluating S-expression commands."""

    def eval(self, input: str) -> str: ...

class Server:
    """Background embedded HTTP server."""

    @property
    def port(self) -> int: ...
    @property
    def url(self) -> str: ...
    def stop(self) -> None: ...
    def __enter__(self) -> "Server": ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> bool: ...

class ValType:
    """Component model value type descriptor."""

    @staticmethod
    def bool() -> "ValType": ...
    @staticmethod
    def s8() -> "ValType": ...
    @staticmethod
    def u8() -> "ValType": ...
    @staticmethod
    def s16() -> "ValType": ...
    @staticmethod
    def u16() -> "ValType": ...
    @staticmethod
    def s32() -> "ValType": ...
    @staticmethod
    def u32() -> "ValType": ...
    @staticmethod
    def s64() -> "ValType": ...
    @staticmethod
    def u64() -> "ValType": ...
    @staticmethod
    def f32() -> "ValType": ...
    @staticmethod
    def f64() -> "ValType": ...
    @staticmethod
    def v128() -> "ValType": ...
    @staticmethod
    def char() -> "ValType": ...
    @staticmethod
    def string() -> "ValType": ...
    @staticmethod
    def list(elem: "ValType") -> "ValType": ...
    @staticmethod
    def record(fields: list[tuple[str, "ValType"]]) -> "ValType": ...
    @staticmethod
    def tuple(items: list["ValType"]) -> "ValType": ...
    @staticmethod
    def variant(cases: list[tuple[str, Optional["ValType"]]]) -> "ValType": ...
    @staticmethod
    def enum_(cases: list[str]) -> "ValType": ...
    @staticmethod
    def option(inner: "ValType") -> "ValType": ...
    @staticmethod
    def result(*, ok: Optional["ValType"] = None, err: Optional["ValType"] = None) -> "ValType": ...
    @staticmethod
    def flags(names: list[str]) -> "ValType": ...
    @property
    def kind(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class Val:
    """Concrete component model value."""

    @staticmethod
    def bool(v: bool) -> "Val": ...
    @staticmethod
    def s8(v: int) -> "Val": ...
    @staticmethod
    def u8(v: int) -> "Val": ...
    @staticmethod
    def s16(v: int) -> "Val": ...
    @staticmethod
    def u16(v: int) -> "Val": ...
    @staticmethod
    def s32(v: int) -> "Val": ...
    @staticmethod
    def u32(v: int) -> "Val": ...
    @staticmethod
    def s64(v: int) -> "Val": ...
    @staticmethod
    def u64(v: int) -> "Val": ...
    @staticmethod
    def f32(v: float) -> "Val": ...
    @staticmethod
    def f64(v: float) -> "Val": ...
    @staticmethod
    def v128(v: int) -> "Val": ...
    @staticmethod
    def char(v: str) -> "Val": ...
    @staticmethod
    def string(v: str) -> "Val": ...
    @staticmethod
    def list(items: list["Val"]) -> "Val": ...
    @staticmethod
    def record(fields: dict[str, "Val"]) -> "Val": ...
    @staticmethod
    def tuple(items: list["Val"]) -> "Val": ...
    @staticmethod
    def variant(case: str, payload: Optional["Val"] = None) -> "Val": ...
    @staticmethod
    def enum_(case: str) -> "Val": ...
    @staticmethod
    def option(val: "Val") -> "Val": ...
    @staticmethod
    def none() -> "Val": ...
    @staticmethod
    def ok(val: Optional["Val"] = None) -> "Val": ...
    @staticmethod
    def err(val: Optional["Val"] = None) -> "Val": ...
    @staticmethod
    def flags(names: list[str]) -> "Val": ...
    @property
    def kind(self) -> str: ...
    @property
    def val_type(self) -> ValType: ...
    def conforms_to(self, ty: ValType) -> bool: ...
    def to_python(self) -> Any: ...
    @staticmethod
    def from_python(ty: ValType, obj: Any) -> "Val": ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class Cnf:
    """A CNF formula in DIMACS format."""

    @property
    def num_vars(self) -> int: ...
    @property
    def num_clauses(self) -> int: ...
    def clauses(self) -> list[list[int]]: ...

class DratProof:
    """A DRAT proof."""

    @property
    def num_steps(self) -> int: ...

class SExp:
    """S-expression node: symbol, string literal, or list."""

    @staticmethod
    def parse(input: str, dialect: str = "covalence") -> list["SExp"]: ...
    @staticmethod
    def symbol(name: str) -> "SExp": ...
    @staticmethod
    def string(data: bytes, format: str = "") -> "SExp": ...
    @staticmethod
    def list(children: list["SExp"]) -> "SExp": ...
    def is_atom(self) -> bool: ...
    def is_list(self) -> bool: ...
    def is_symbol(self) -> bool: ...
    def is_string(self) -> bool: ...
    @property
    def symbol_name(self) -> Optional[str]: ...
    @property
    def string_bytes(self) -> Optional[bytes]: ...
    @property
    def string_format(self) -> Optional[str]: ...
    @property
    def children(self) -> Optional[list["SExp"]]: ...
    def prettyprint(self) -> str: ...
    def map(self, f: Callable[["SExp"], Any]) -> "PySExp": ...
    def to_py(self) -> "PySExp": ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> "SExp": ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class PySExp:
    """S-expression node with Python object atoms."""

    @staticmethod
    def atom(value: object) -> "PySExp": ...
    @staticmethod
    def list(children: list["PySExp"]) -> "PySExp": ...
    def is_atom(self) -> bool: ...
    def is_list(self) -> bool: ...
    @property
    def value(self) -> Optional[object]: ...
    @property
    def children(self) -> Optional[list["PySExp"]]: ...
    def map(self, f: Callable[[Any], Any]) -> "PySExp": ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> "PySExp": ...
    def __repr__(self) -> str: ...

class TreeStoreProtocol:
    """Protocol for Python-backed tree stores (informational, not enforced at type level).

    Required: set, get, ns, dup.
    Optional: touch, touched.
    """

    def set(self, key: bytes, value: bytes) -> None: ...
    def get(self, key: bytes) -> Optional[bytes]: ...
    def ns(self, key: bytes) -> "TreeStoreProtocol": ...
    def dup(self) -> "TreeStoreProtocol": ...
    def touch(self, key: bytes) -> None: ...
    def touched(self, key: bytes) -> bool: ...

class TreeStore:
    """Hierarchical tree store — POSIX-style virtual filesystem."""

    def __init__(self, obj: TreeStoreProtocol) -> None: ...
    @staticmethod
    def memory() -> "TreeStore": ...
    def set(self, key: bytes, value: bytes) -> None: ...
    def get(self, key: bytes) -> Optional[bytes]: ...
    def touch(self, key: bytes) -> None: ...
    def touched(self, key: bytes) -> bool: ...
    def ns(self, key: bytes) -> "TreeStore": ...
    def dup(self) -> "TreeStore": ...
    def __repr__(self) -> str: ...

class KvStore:
    """Async key-value store driven as a blocking API.

    Abstract base class — instantiate a subclass (`MemoryKvStore`,
    `AwsKvStore`, `S3KvStore`).
    """

    def get(self, key: str) -> bytes: ...
    def get_range(self, key: str, start: int, end: int) -> bytes: ...
    def put(self, key: str, value: bytes) -> None: ...
    def delete(self, key: str) -> None: ...
    def head(self, key: str) -> dict: ...
    def __repr__(self) -> str: ...

class MemoryKvStore(KvStore):
    """In-memory KV store, backed by Rust. Useful for tests."""

    def __init__(self) -> None: ...

class AwsKvStore(KvStore):
    """AWS S3 using the default credential chain."""

    def __init__(self, bucket: str, region: str) -> None: ...

class S3KvStore(KvStore):
    """S3-compatible endpoint (Wasabi, B2, R2, MinIO, ...). Path-style by default."""

    def __init__(
        self,
        endpoint: str,
        region: str,
        bucket: str,
        access_key_id: str,
        secret_access_key: str,
        *,
        allow_http: bool = False,
        virtual_hosted_style: bool = False,
    ) -> None: ...

class Principal:
    """An authenticated entity (wraps an Ed25519 public key)."""

    def __init__(self, bytes: bytes) -> None: ...
    def bytes(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

class Signature:
    """An opaque detached signature over some data."""

    def verify(self, principal: Principal, data: bytes) -> bool: ...
    def __repr__(self) -> str: ...

class Signer:
    """A signing capability (wraps an Ed25519 keypair)."""

    @staticmethod
    def generate() -> "Signer": ...
    def principal(self) -> Principal: ...
    def sign(self, data: bytes) -> Signature: ...
    def __repr__(self) -> str: ...

# Backend constructors
def local(store: Optional[Store] = None) -> Backend: ...
def local_persistent(path: str) -> Backend: ...
def session_local() -> Session: ...
def serve(port: int = 0, store: Optional[str] = None) -> Server: ...

# Hasher constructors
def blake3() -> Hasher: ...
def blake3_keyed(key: O256) -> Hasher: ...
def blake3_kdf(ctx: str) -> Hasher: ...
def sha256() -> Hasher: ...
def hasher(name: str) -> Hasher: ...

# Git hashers
def git_sha1() -> GitHasher: ...
def git_sha256() -> GitHasher: ...
def git_tree_to_dir_rows(
    data: bytes,
    hash_map: Optional[dict[bytes, O256]] = None,
    hash_len: int = 20,
) -> list[dict[str, object]]:
    """Parse git tree bytes into directory rows.

    hash_map: maps raw git hash bytes -> O256.
      - Required for SHA-1 (hash_len=20).
      - Optional for SHA-256 (hash_len=32): None means identity mapping.
    Raises ValueError if hash_map is None and hash_len != 32, or if a hash is missing.
    """
    ...

# S-expression parsing
def parse_sexp(input: str) -> list[SExp]: ...
def parse_sexp_smt(input: str) -> list[SExp]: ...
def parse_sexp_wat(input: str) -> list[SExp]: ...

# SAT / DRAT
def parse_dimacs_str(text: str) -> Cnf: ...
def parse_drat_text_str(text: str) -> DratProof: ...
def parse_drat_binary_bytes(data: bytes) -> DratProof: ...
def check_drat(cnf: Cnf, proof: DratProof) -> bool: ...
def load_dimacs(path: str) -> Cnf: ...
def load_drat(path: str, binary: Optional[bool] = None) -> DratProof: ...

# Compression
def read_compressed(path: str) -> bytes: ...

# LLM bindings (only present when built with `--features llm`)
class ChatMessage:
    """A single chat message (role + content)."""

    def __init__(self, role: str, content: str) -> None: ...
    @staticmethod
    def system(content: str) -> "ChatMessage": ...
    @staticmethod
    def user(content: str) -> "ChatMessage": ...
    @staticmethod
    def assistant(content: str) -> "ChatMessage": ...
    @property
    def role(self) -> str: ...
    @property
    def content(self) -> str: ...

class ChatOptions:
    """Per-request sampling knobs. Backends ignore fields they don't support."""

    def __init__(
        self,
        temperature: Optional[float] = None,
        top_p: Optional[float] = None,
        max_tokens: Optional[int] = None,
        seed: Optional[int] = None,
        stop: Optional[list[str]] = None,
    ) -> None: ...
    @property
    def temperature(self) -> Optional[float]: ...
    @property
    def top_p(self) -> Optional[float]: ...
    @property
    def max_tokens(self) -> Optional[int]: ...
    @property
    def seed(self) -> Optional[int]: ...
    @property
    def stop(self) -> list[str]: ...

class ChatRequest:
    def __init__(
        self,
        model: str,
        messages: list[ChatMessage],
        options: Optional[ChatOptions] = None,
    ) -> None: ...
    @property
    def model(self) -> str: ...
    @property
    def messages(self) -> list[ChatMessage]: ...
    @property
    def options(self) -> ChatOptions: ...

class TokenUsage:
    @property
    def prompt_tokens(self) -> Optional[int]: ...
    @property
    def completion_tokens(self) -> Optional[int]: ...

class ChatResponse:
    @property
    def message(self) -> ChatMessage: ...
    @property
    def content(self) -> str: ...
    @property
    def role(self) -> str: ...
    @property
    def finish_reason(self) -> str: ...
    @property
    def usage(self) -> TokenUsage: ...

class Llm:
    """High-level chat client. Subclasses pick the provider.

    The blocking `chat` / `complete` calls release the GIL, so callers can wrap
    them in `asyncio.to_thread(...)` until a native asyncio binding lands.
    """

    @property
    def model(self) -> str: ...
    @property
    def options(self) -> ChatOptions: ...
    def chat(self, messages: list[ChatMessage]) -> ChatResponse: ...
    def complete(self, prompt: str) -> str: ...
    def chat_request(self, req: ChatRequest) -> ChatResponse: ...

class Ollama(Llm):
    """Local Ollama via its OpenAI-compatible `/v1` endpoint."""

    def __init__(self, model: str, base_url: Optional[str] = None) -> None: ...
    @staticmethod
    def from_env(model: str) -> "Ollama": ...

class OpenAI(Llm):
    """OpenAI (api.openai.com). `api_key` required."""

    def __init__(self, api_key: str, model: str) -> None: ...
    @staticmethod
    def from_env(model: str) -> "OpenAI": ...

class Groq(Llm):
    """Groq via OpenAI-compatible endpoint."""

    def __init__(self, api_key: str, model: str) -> None: ...
    @staticmethod
    def from_env(model: str) -> "Groq": ...

class Cerebras(Llm):
    """Cerebras via OpenAI-compatible endpoint."""

    def __init__(self, api_key: str, model: str) -> None: ...
    @staticmethod
    def from_env(model: str) -> "Cerebras": ...

class DeepSeek(Llm):
    """DeepSeek via OpenAI-compatible endpoint."""

    def __init__(self, api_key: str, model: str) -> None: ...
    @staticmethod
    def from_env(model: str) -> "DeepSeek": ...

class OpenAICompat(Llm):
    """Generic OpenAI-compatible endpoint at a custom `base_url`."""

    def __init__(self, base_url: str, model: str, api_key: Optional[str] = None) -> None: ...

OPENAI_BASE_URL: str
ANTHROPIC_BASE_URL: str
GROQ_BASE_URL: str
CEREBRAS_BASE_URL: str
DEEPSEEK_BASE_URL: str
OLLAMA_BASE_URL: str

# wasm_store submodule
class wasm_store:
    """WASM-component-backed content stores.

    Components are built via the `build_*` functions and wrapped as
    `WasmStore` instances. Composers (`merge`, `s3_path`) take other
    `WasmStore`s as backings.
    """

    class WasmStore:
        @staticmethod
        def from_bytes(bytes: bytes) -> "wasm_store.WasmStore": ...
        @staticmethod
        def from_kv(kv: "KvStore") -> "wasm_store.WasmStore": ...
        @staticmethod
        def compose(
            bytes: bytes, backings: list["wasm_store.WasmStore"]
        ) -> "wasm_store.WasmStore": ...
        def get(self, key: bytes) -> bytes: ...
        def try_get(self, key: bytes) -> Optional[bytes]: ...
        def contains(self, key: bytes) -> bool: ...
        def head(self, key: bytes) -> Optional[int]: ...

    @staticmethod
    def build_single_blob(key: bytes, blob: bytes) -> bytes: ...
    @staticmethod
    def build_merge_composer() -> bytes: ...
    @staticmethod
    def build_s3_path_composer(prefix: str) -> bytes: ...
    @staticmethod
    def hex_encode(data: bytes) -> str: ...

# Module-level convenience functions (lazy default backend)
def store(data: Union[bytes, str, Component]) -> O256: ...
def store_str(text: str) -> O256: ...
def get(hash: Union[O256, str]) -> Optional[bytes]: ...
def has(hash: Union[O256, str]) -> bool: ...
def compile_wat(wat: str) -> O256: ...
def decide(hash: Union[O256, str, Component]) -> dict[str, object]: ...
