"""Type stubs for the covalence native module (PyO3)."""

from typing import Optional, Union

class O256:
    """256-bit hash value. Also acts as a BLAKE3 keyed-hash key."""

    @staticmethod
    def from_hex(hex: str) -> "O256": ...
    @staticmethod
    def from_bytes(data: bytes) -> "O256": ...
    @staticmethod
    def blob(data: bytes) -> "O256": ...
    @property
    def hex(self) -> str: ...
    def hash(self, data: bytes) -> "O256": ...
    def hash_file(self, path: str) -> "O256": ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Component:
    """Validated WASM component with cached metadata."""

    @staticmethod
    def from_wat(text: str) -> "Component": ...
    @staticmethod
    def from_bytes(data: bytes) -> "Component": ...
    @property
    def bytes(self) -> bytes: ...
    @property
    def imports(self) -> list[str]: ...
    @property
    def exports(self) -> list[str]: ...
    @property
    def wat(self) -> str: ...
    @property
    def hash(self) -> O256: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class GitObject:
    """Git object hash (SHA-1 or SHA-256)."""

    @property
    def hex(self) -> str: ...
    @property
    def kind(self) -> str: ...
    def to_o256(self) -> O256: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class Hasher:
    """Hashing strategy that produces O256 values."""

    def hash(self, data: bytes) -> O256: ...
    def hash_file(self, path: str) -> O256: ...

class GitHasher:
    """Git hashing strategy that produces GitObject values."""

    def hash_blob(self, data: bytes) -> GitObject: ...
    def hash_blob_file(self, path: str) -> GitObject: ...
    def hash_tree(self, data: bytes) -> GitObject: ...

class StoreProtocol:
    """Protocol for Python-backed stores (informational, not enforced at type level)."""

    def get(self, key: O256) -> Optional[bytes]: ...
    def put(self, key: O256, data: bytes) -> None: ...
    def insert(self, data: bytes) -> O256: ...
    def contains(self, key: O256) -> bool: ...
    def __len__(self) -> int: ...

class Store:
    """Content-addressed blob store."""

    def __init__(self, obj: StoreProtocol) -> None: ...
    @staticmethod
    def memory() -> "Store": ...
    @staticmethod
    def sqlite(path: str) -> "Store": ...
    def insert(self, data: bytes) -> O256: ...
    def get(self, key: Union[O256, str]) -> Optional[bytes]: ...
    def put(self, key: Union[O256, str], data: bytes) -> None: ...
    def contains(self, key: Union[O256, str]) -> bool: ...
    def __contains__(self, key: Union[O256, str]) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class Backend:
    """Covalence backend: content store + WASM engine on a background thread."""

    def store(self, data: Union[bytes, str, "Component"]) -> O256: ...
    def store_blob(self, data: bytes) -> O256: ...
    def store_str(self, text: str) -> O256: ...
    def get_blob(self, hash: Union[O256, str]) -> Optional[bytes]: ...
    def has_blob(self, hash: Union[O256, str]) -> bool: ...
    def blob_count(self) -> Optional[int]: ...
    def compile_wat(self, wat: str) -> O256: ...
    def decide(self, hash: Union[O256, str, "Component"]) -> dict[str, object]: ...
    def info(self) -> dict[str, str]: ...

class Session:
    """REPL session for evaluating S-expression commands."""

    def eval(self, input: str) -> str: ...

class Server:
    """Background embedded HTTP server."""

    @property
    def port(self) -> int: ...
    @property
    def url(self) -> str: ...
    def stop(self) -> None: ...
    def __enter__(self) -> "Server": ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> bool: ...

def local(store: Optional[Store] = None) -> Backend: ...
def local_persistent(path: str) -> Backend: ...
def session_local() -> Session: ...
def serve(port: int = 0, store: Optional[str] = None) -> Server: ...
def blake3() -> Hasher: ...
def blake3_keyed(key: O256) -> Hasher: ...
def blake3_kdf(ctx: str) -> Hasher: ...
def sha256() -> Hasher: ...
def hasher(name: str) -> Hasher: ...
def git_sha1() -> GitHasher: ...
def git_sha256() -> GitHasher: ...

# Module-level convenience functions (lazy default backend)
def store(data: Union[bytes, str, Component]) -> O256: ...
def store_str(text: str) -> O256: ...
def get(hash: Union[O256, str]) -> Optional[bytes]: ...
def has(hash: Union[O256, str]) -> bool: ...
def compile_wat(wat: str) -> O256: ...
def decide(hash: Union[O256, str, Component]) -> dict[str, object]: ...
