(component
    (import "attest" (func $attest))
    (import "cov:blob/api" (instance $blob-api
        (export "blob" (type (sub resource)))
        (export "[method]blob.read" (func (param "self" (borrow 0)) (result (list u8))))
        (export "[method]blob.eq" (func (param "self" (borrow 0)) (param "other" (borrow 0)) (result bool)))
    ))
    (alias export $blob-api "blob" (type $blob))
    (import "cov:sign/api" (instance $sign-api
        (export "principal" (type (sub resource)))
        (export "signature" (type (sub resource)))
        (export "signer" (type (sub resource)))
        (export "[constructor]principal" (func (param "bytes" (list u8)) (result (own 0))))
        (export "[method]signer.principal" (func (param "self" (borrow 2)) (result (own 0))))
        (export "[method]principal.bytes" (func (param "self" (borrow 0)) (result (list u8))))
        (export "[method]principal.eq" (func (param "self" (borrow 0)) (param "other" (borrow 0)) (result bool)))
    ))
    (alias export $sign-api "principal" (type $principal))
    (alias export $sign-api "signature" (type $signature))
    (alias export $sign-api "signer" (type $signer))
    (alias export $sign-api "[constructor]principal" (func $principal-new))
    (alias export $sign-api "[method]signer.principal" (func $signer-principal))
    (alias export $sign-api "[method]principal.bytes" (func $principal-bytes))
    (alias export $sign-api "[method]principal.eq" (func $principal-eq))
    (import "generate-signer" (func $generate-signer (result (own $signer))))

    ;; Allocator for list lowering/lifting
    (core module $alloc_mod
        (memory 1)
        (export "memory" (memory 0))
        (func $realloc (param i32 i32 i32 i32) (result i32)
            (i32.const 0x1000)
        )
        (export "cabi_realloc" (func $realloc))
    )
    (core instance $alloc (instantiate $alloc_mod))
    (alias core export $alloc "memory" (core memory $mem))
    (alias core export $alloc "cabi_realloc" (core func $realloc_fn))

    (core func $attest_lowered (canon lower (func $attest)))
    (core func $generate_signer_lowered (canon lower (func $generate-signer)))
    (core func $signer_principal_lowered (canon lower (func $signer-principal)))
    (core func $principal_bytes_lowered (canon lower (func $principal-bytes) (memory $mem) (realloc $realloc_fn)))
    (core func $principal_new_lowered (canon lower (func $principal-new) (memory $mem) (realloc $realloc_fn)))
    (core func $principal_eq_lowered (canon lower (func $principal-eq)))
    (core func $signer_drop (canon resource.drop $signer))
    (core func $principal_drop (canon resource.drop $principal))

    (core module $m
        (import "alloc" "memory" (memory 1))
        (import "env" "attest" (func $attest))
        (import "env" "generate-signer" (func $generate_signer (result i32)))
        (import "env" "signer-principal" (func $signer_principal (param i32) (result i32)))
        ;; principal-bytes: (borrow) -> retptr writes (ptr, len)
        (import "env" "principal-bytes" (func $principal_bytes (param i32 i32)))
        ;; principal-new: (ptr, len) -> own<principal>
        (import "env" "principal-new" (func $principal_new (param i32 i32) (result i32)))
        (import "env" "principal-eq" (func $principal_eq (param i32 i32) (result i32)))
        (import "env" "signer-drop" (func $signer_drop (param i32)))
        (import "env" "principal-drop" (func $principal_drop (param i32)))
        (func $start
            (local $signer i32)
            (local $p1 i32)
            (local $p2 i32)
            (local $ptr i32)
            (local $len i32)
            ;; Generate signer, get principal
            (local.set $signer (call $generate_signer))
            (local.set $p1 (call $signer_principal (local.get $signer)))
            ;; Get bytes: writes (ptr, len) at retptr=0
            (call $principal_bytes (local.get $p1) (i32.const 0))
            (local.set $ptr (i32.load (i32.const 0)))
            (local.set $len (i32.load (i32.const 4)))
            ;; Construct new principal from those bytes
            (local.set $p2 (call $principal_new (local.get $ptr) (local.get $len)))
            ;; p1 == p2 should be true
            (if (i32.eqz (call $principal_eq (local.get $p1) (local.get $p2)))
                (then (unreachable))
            )
            ;; All checks passed
            (call $attest)
            ;; Cleanup
            (call $signer_drop (local.get $signer))
            (call $principal_drop (local.get $p1))
            (call $principal_drop (local.get $p2))
        )
        (start $start)
    )
    (core instance $i (instantiate $m
        (with "alloc" (instance $alloc))
        (with "env" (instance
            (export "attest" (func $attest_lowered))
            (export "generate-signer" (func $generate_signer_lowered))
            (export "signer-principal" (func $signer_principal_lowered))
            (export "principal-bytes" (func $principal_bytes_lowered))
            (export "principal-new" (func $principal_new_lowered))
            (export "principal-eq" (func $principal_eq_lowered))
            (export "signer-drop" (func $signer_drop))
            (export "principal-drop" (func $principal_drop))
        ))
    ))
)
