//! Reference WASM **components** that name mathematical functions by
//! content-addressed hash. The hash of each `.wasm` + its WIT signature is
//! the function's identity. Multiple variants per algorithm coexist on
//! purpose: different hashes naming the same mathematical function are
//! valuable proof targets.
//!
//! The default build has no toolchain dependency beyond rustc. The
//! `.wat`, `.wasm`, and `.wit` artifacts are committed and read via
//! `include_*!`. Regeneration is done via the separate `rebuild` binary
//! (cargo run -p covalence-wasm-spec --bin rebuild).

#![forbid(unsafe_code)]

pub mod compose;
pub use compose::{ComposeError, Shape, compose_one_shot, compose_one_shot_with, detect_shape};

use covalence_hash::O256;

/// One reference component naming a mathematical function by hash.
///
/// All `'a` references are typically `'static` and point at compile-time
/// constants generated by `build.rs`. The `bytes` feature gates the
/// asset payload (`wit`, `wat`, `wasm`, KATs, linked spec list) so a
/// downstream crate can depend on `covalence-wasm-spec` purely for the
/// hash constants without paying the binary-size cost of the embedded
/// wasm bytes.
#[derive(Debug)]
pub struct Spec<'a> {
    pub name: &'a str,
    pub variant: &'a str,
    pub blake3: O256,
    pub sha256: [u8; 32],
    pub kind: SpecKind<'a>,
    pub meta: Metadata<'a>,
    #[cfg(feature = "bytes")]
    pub wit: &'a str,
    #[cfg(feature = "bytes")]
    pub wat: &'a str,
    #[cfg(feature = "bytes")]
    pub wasm: &'a [u8],
    #[cfg(feature = "bytes")]
    pub kats: &'a [Kat<'a>],
    #[cfg(feature = "bytes")]
    pub linked: &'a [&'a Spec<'a>],
}

/// Coarse classification of what a spec computes. Drives test harness
/// generation: hash specs run KATs + differential tests against
/// `covalence-hash`; sig specs verify against an embedded message hash.
#[derive(Debug)]
pub enum SpecKind<'a> {
    Hash(HashProperties),
    Sign(SignProperties<'a>),
}

/// Structural facts about a hash function: enough for downstream code to
/// pick the right block size, decide whether HMAC is sensible, etc. The
/// `modes` slice enumerates which canonical-ABI modes the component
/// supports — not all hashes are usable as MACs, etc.
#[derive(Debug)]
pub struct HashProperties {
    pub output_bits: u32,
    pub block_bits: u32,
    pub state_bits: u32,
    pub length_extendable: bool,
    pub keyed: bool,
    pub xof: bool,
    pub modes: &'static [HashMode],
}

/// Per-spec modes a hash function supports.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HashMode {
    Hash,
    KeyedHash,
    DeriveKey,
    Hmac,
}

#[derive(Debug)]
pub struct SignProperties<'a> {
    pub public_key_bytes: u32,
    pub signature_bytes: u32,
    pub deterministic_verify: bool,
    pub deterministic_sign: bool,
    pub message_hashing: Option<&'a Spec<'a>>,
}

#[derive(Debug)]
pub struct Metadata<'a> {
    pub description: &'a str,
    pub spec_docs: &'a [SpecDoc<'a>],
}

#[derive(Debug)]
pub struct SpecDoc<'a> {
    pub title: &'a str,
    pub url: &'a str,
    pub local_path: Option<&'a str>,
}

/// Known-Answer-Test vector. `expected` is compared bit-equal with the
/// component output; for streaming KATs the harness feeds `input` to the
/// component in arbitrary cuts.
///
/// For `Verify` KATs the field semantics differ:
///   * `input`    = message bytes,
///   * `key`      = public key (32 bytes for Ed25519),
///   * `expected` = signature bytes (64 bytes for Ed25519),
///   * `expected_result` = expected `verify` return (`true` for an
///     accept vector, `false` for a reject vector).
/// For all other modes `expected_result` is unused (defaults to `true`).
#[cfg(feature = "bytes")]
#[derive(Debug)]
pub struct Kat<'a> {
    pub name: &'a str,
    pub mode: KatMode,
    pub input: &'a [u8],
    pub key: Option<&'a [u8]>,
    pub expected: &'a [u8],
    pub expected_result: bool,
}

/// Selects which of the spec's exports a `Kat` exercises.
///
/// * `OneShot` / `Streaming` — drive the spec's plain `hash` export
///   (one-shot or chunked through update*) and compare against
///   `expected`.
/// * `Compress` — call the `compress(state, block)` primitive
///   directly; `input` is expected to be `state || block`.
/// * `KeyedHash` — call the spec's `keyed-hash(key, data)` export.
///   `key` must be present.
/// * `DeriveKey` — call the spec's `derive-key(context, key-material)`
///   export. `key` is the UTF-8 context string and `input` is the
///   key material.
#[cfg(feature = "bytes")]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KatMode {
    OneShot,
    Streaming,
    Compress,
    KeyedHash,
    DeriveKey,
    /// Sign-spec verification KAT. `key` carries the public key,
    /// `input` the message, `expected` the signature; `expected_result`
    /// is the boolean the `verify` export must return.
    Verify,
}

/// Hash constants of every committed variant. Always present, no
/// `bytes` feature required.
pub mod hashes {
    include!(concat!(env!("OUT_DIR"), "/hashes.rs"));
}

/// Embedded `.wat` / `.wasm` / `.wit` sources for every committed
/// variant. Gated by the `bytes` feature.
#[cfg(feature = "bytes")]
pub mod bytes {
    include!(concat!(env!("OUT_DIR"), "/bytes.rs"));
}

/// The full list of every `Spec` known to this build. Gated by `bytes`
/// because each entry references the embedded asset bytes.
#[cfg(feature = "bytes")]
pub mod registry {
    #[allow(unused_imports)]
    use super::{
        HashMode, HashProperties, Kat, KatMode, Metadata, SignProperties, Spec, SpecDoc, SpecKind,
    };
    include!(concat!(env!("OUT_DIR"), "/registry.rs"));
}

#[cfg(feature = "bytes")]
pub use registry::ALL_SPECS;
