#!/usr/bin/env bun
// Generate the internal crate dependency graph + the TCB closure from
// `cargo metadata` (resolve only — no compile). Emits deterministic artifacts
// under notes/deps/ so the graph (and especially the TCB) is tracked in git:
//
//   notes/deps/graph.json   machine-readable nodes + edges + tcb
//   notes/deps/tcb.json     the TCB closure (workspace + external) — watch this
//   notes/deps/graph.mmd    Mermaid (renders on GitHub; TCB highlighted)
//   notes/deps/graph.dot    Graphviz DOT (TCB highlighted)
//   notes/deps/graph.svg    rendered from DOT iff `dot` is on PATH (best-effort)
//
// Usage:
//   bun scripts/dep-graph.mjs           regenerate the artifacts
//   bun scripts/dep-graph.mjs --check   fail (exit 1) if any artifact is stale
//                                        (used in CI + the pre-commit hook)
//
// The TCB = the normal-dependency closure of `covalence-core` + `covalence-pure`.
// A change to tcb.json means the trusted base grew/shrank — review it.

import { execSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";

const CHECK = process.argv.includes("--check");
const OUT_DIR = "notes/deps";
const TCB_ROOTS = ["covalence-core", "covalence-pure"];

// ---------------------------------------------------------------------------
// Load the resolved metadata.
// ---------------------------------------------------------------------------
const md = JSON.parse(
  execSync("cargo metadata --format-version 1", { maxBuffer: 1 << 30 }).toString(),
);
const wsIds = new Set(md.workspace_members);
const byId = new Map(md.packages.map((p) => [p.id, p]));
const wsNames = new Set(
  md.packages.filter((p) => wsIds.has(p.id)).map((p) => p.name),
);
const idByName = new Map(
  md.packages.filter((p) => wsIds.has(p.id)).map((p) => [p.name, p.id]),
);
const short = (n) => n.replace(/^covalence-/, "");
const isNormal = (kinds) => kinds.some((k) => k.kind === null || k.kind === "normal");

// ---------------------------------------------------------------------------
// Internal edges: workspace covalence-* -> workspace covalence-* (normal deps).
// ---------------------------------------------------------------------------
const edgeSet = new Set();
for (const p of md.packages) {
  if (!wsIds.has(p.id)) continue;
  for (const d of p.dependencies) {
    if (d.kind && d.kind !== "normal") continue; // skip dev / build deps
    if (wsNames.has(d.name)) edgeSet.add(`${p.name}\t${d.name}`);
  }
}
const nodes = [...wsNames].sort();
const edges = [...edgeSet]
  .map((e) => e.split("\t"))
  .sort((a, b) => a[0].localeCompare(b[0]) || a[1].localeCompare(b[1]));

// ---------------------------------------------------------------------------
// TCB closure: normal-dep transitive closure of the trusted roots, via resolve.
// ---------------------------------------------------------------------------
const resolveById = new Map((md.resolve?.nodes ?? []).map((n) => [n.id, n]));
function closure(rootName) {
  const rootId = idByName.get(rootName);
  const out = new Set();
  const stack = rootId ? [rootId] : [];
  while (stack.length) {
    const id = stack.pop();
    if (out.has(id)) continue;
    out.add(id);
    const node = resolveById.get(id);
    if (!node) continue;
    for (const dep of node.deps) {
      if (isNormal(dep.dep_kinds)) stack.push(dep.pkg);
    }
  }
  return out;
}
const tcbIds = new Set(TCB_ROOTS.flatMap((r) => [...closure(r)]));
const tcbNames = [...tcbIds].map((id) => byId.get(id).name);
const tcb = {
  roots: [...TCB_ROOTS].sort(),
  workspace: tcbNames.filter((n) => wsNames.has(n)).sort(),
  external: tcbNames.filter((n) => !wsNames.has(n)).sort(),
};
const tcbWs = new Set(tcb.workspace);

// ---------------------------------------------------------------------------
// Render artifacts (deterministic).
// ---------------------------------------------------------------------------
const graphJson =
  JSON.stringify(
    {
      generatedBy: "scripts/dep-graph.mjs",
      note: "Regenerate with `bun run deps`. Internal covalence-* normal-dependency edges only.",
      nodes,
      edges: edges.map(([from, to]) => ({ from, to })),
      tcb,
    },
    null,
    2,
  ) + "\n";

const tcbJson = JSON.stringify(tcb, null, 2) + "\n";

const mmd =
  [
    "%% Generated by scripts/dep-graph.mjs — do not edit (run `bun run deps`).",
    "graph LR",
    ...edges.map(([from, to]) => `  ${short(from)} --> ${short(to)}`),
    "  classDef tcb fill:#ffd6d6,stroke:#cc0000,color:#000;",
    tcb.workspace.length
      ? `  class ${tcb.workspace.map(short).join(",")} tcb;`
      : "",
  ]
    .filter(Boolean)
    .join("\n") + "\n";

const dot =
  [
    "// Generated by scripts/dep-graph.mjs — do not edit (run `bun run deps`).",
    "digraph deps {",
    "  rankdir=LR;",
    '  node [shape=box, fontname="sans-serif"];',
    ...nodes.map(
      (n) =>
        `  "${short(n)}"${tcbWs.has(n) ? ' [style=filled, fillcolor="#ffd6d6"]' : ""};`,
    ),
    ...edges.map(([from, to]) => `  "${short(from)}" -> "${short(to)}";`),
    "}",
  ].join("\n") + "\n";

const artifacts = {
  [`${OUT_DIR}/graph.json`]: graphJson,
  [`${OUT_DIR}/tcb.json`]: tcbJson,
  [`${OUT_DIR}/graph.mmd`]: mmd,
  [`${OUT_DIR}/graph.dot`]: dot,
};

// ---------------------------------------------------------------------------
// Check or write.
// ---------------------------------------------------------------------------
if (CHECK) {
  const stale = Object.entries(artifacts).filter(
    ([path, content]) =>
      !existsSync(path) || readFileSync(path, "utf8") !== content,
  );
  if (stale.length) {
    console.error("dep-graph: artifacts are stale — run `bun run deps`:");
    for (const [path] of stale) console.error(`  ${path}`);
    process.exit(1);
  }
  console.error("dep-graph: up to date");
  process.exit(0);
}

mkdirSync(OUT_DIR, { recursive: true });
for (const [path, content] of Object.entries(artifacts)) writeFileSync(path, content);

// Best-effort SVG (only if graphviz is installed; not part of --check).
try {
  execSync(`dot -Tsvg "${OUT_DIR}/graph.dot" -o "${OUT_DIR}/graph.svg"`, {
    stdio: "ignore",
  });
  console.error(`dep-graph: wrote ${Object.keys(artifacts).length} artifacts + graph.svg`);
} catch {
  console.error(
    `dep-graph: wrote ${Object.keys(artifacts).length} artifacts (graphviz \`dot\` not found — skipped graph.svg)`,
  );
}
