import { describe, it, expect } from 'vitest';
import { decodeGraph, hexToBytes, CANONICAL_MAGIC, CANONICAL_VERSION } from './decode.js';

// Fixture generated by covalence-python (see comment in
// apps/covalence-web/src/routes/graph/+page.svelte):
//   #0 "src"    (ordered)  one output  type 1
//   #1 "effect" (ordered)  one input type 1, one output type 2
//   #2 "sink"   (pure)     one input  type 2
const EXAMPLE_HEX =
	'434f5647010301010101036f75740001037372630102000102696e0102036f757400010665666665637' +
	'40001000202696e00010473696e6b020000010001010200';

describe('decodeGraph', () => {
	it('parses magic + version', () => {
		const data = hexToBytes(EXAMPLE_HEX);
		expect(data[0]).toBe(CANONICAL_MAGIC[0]);
		expect(data[4]).toBe(CANONICAL_VERSION);
	});

	it('decodes 3 nodes / 2 edges with labels + kinds', () => {
		const g = decodeGraph(hexToBytes(EXAMPLE_HEX));
		expect(g.version).toBe(1);
		expect(g.nodes).toHaveLength(3);
		expect(g.edges).toHaveLength(2);

		expect(g.nodes[0].kind).toBe('ordered');
		expect(g.nodes[0].label).toBe('src');
		expect(g.nodes[1].kind).toBe('ordered');
		expect(g.nodes[1].label).toBe('effect');
		expect(g.nodes[2].kind).toBe('pure');
		expect(g.nodes[2].label).toBe('sink');

		expect(g.edges[0]).toEqual({ fromNode: 0, fromPort: 0, toNode: 1, toPort: 0 });
		expect(g.edges[1]).toEqual({ fromNode: 1, fromPort: 1, toNode: 2, toPort: 0 });
	});

	it('rejects bad magic', () => {
		const bad = hexToBytes('4e4f504501' + '00'.repeat(20));
		expect(() => decodeGraph(bad)).toThrow(/bad magic/);
	});

	it('rejects truncated input', () => {
		expect(() => decodeGraph(hexToBytes('434f56'))).toThrow(/truncated/);
	});

	it('hexToBytes handles whitespace and 0x prefix', () => {
		const a = hexToBytes('0x434f');
		expect(Array.from(a)).toEqual([0x43, 0x4f]);
		const b = hexToBytes('43 4f');
		expect(Array.from(b)).toEqual([0x43, 0x4f]);
	});
});
