(component
    (import "attest" (func $attest))
    (import "cov:blob/api" (instance $blob-api
        (export "blob" (type (sub resource)))
        (export "[method]blob.read" (func (param "self" (borrow 0)) (result (list u8))))
        (export "[method]blob.eq" (func (param "self" (borrow 0)) (param "other" (borrow 0)) (result bool)))
    ))
    (alias export $blob-api "blob" (type $blob))
    (import "cov:sign/api" (instance $sign-api
        (export "principal" (type (sub resource)))
        (export "signature" (type (sub resource)))
        (export "signer" (type (sub resource)))
        (export "[method]signer.principal" (func (param "self" (borrow 2)) (result (own 0))))
        (export "[method]signer.sign" (func (param "self" (borrow 2)) (param "data" (borrow $blob)) (result (own 1))))
        (export "[method]signature.verify" (func (param "self" (borrow 1)) (param "by" (borrow 0)) (param "data" (borrow $blob)) (result bool)))
    ))
    (alias export $sign-api "principal" (type $principal))
    (alias export $sign-api "signature" (type $signature))
    (alias export $sign-api "signer" (type $signer))
    (alias export $sign-api "[method]signer.principal" (func $signer-principal))
    (alias export $sign-api "[method]signer.sign" (func $signer-sign))
    (alias export $sign-api "[method]signature.verify" (func $sig-verify))
    (import "generate-signer" (func $generate-signer (result (own $signer))))
    (import "blob-{hash_hex}" (func $get-blob (result (own $blob))))

    (core func $attest_lowered (canon lower (func $attest)))
    (core func $generate_signer_lowered (canon lower (func $generate-signer)))
    (core func $get_blob_lowered (canon lower (func $get-blob)))
    (core func $signer_principal_lowered (canon lower (func $signer-principal)))
    (core func $signer_sign_lowered (canon lower (func $signer-sign)))
    (core func $sig_verify_lowered (canon lower (func $sig-verify)))
    (core func $signer_drop (canon resource.drop $signer))
    (core func $principal_drop (canon resource.drop $principal))
    (core func $signature_drop (canon resource.drop $signature))
    (core func $blob_drop (canon resource.drop $blob))

    (core module $m
        (import "env" "attest" (func $attest))
        (import "env" "generate-signer" (func $generate_signer (result i32)))
        (import "env" "get-blob" (func $get_blob (result i32)))
        (import "env" "signer-principal" (func $signer_principal (param i32) (result i32)))
        (import "env" "signer-sign" (func $signer_sign (param i32 i32) (result i32)))
        (import "env" "sig-verify" (func $sig_verify (param i32 i32 i32) (result i32)))
        (import "env" "signer-drop" (func $signer_drop (param i32)))
        (import "env" "principal-drop" (func $principal_drop (param i32)))
        (import "env" "signature-drop" (func $signature_drop (param i32)))
        (import "env" "blob-drop" (func $blob_drop (param i32)))
        (func $start
            (local $signer i32)
            (local $blob i32)
            (local $principal i32)
            (local $sig i32)
            ;; Generate a signer, get a blob
            (local.set $signer (call $generate_signer))
            (local.set $blob (call $get_blob))
            ;; Sign the blob
            (local.set $sig (call $signer_sign (local.get $signer) (local.get $blob)))
            ;; Get the principal
            (local.set $principal (call $signer_principal (local.get $signer)))
            ;; Verify: should return true (1)
            (if (call $sig_verify (local.get $sig) (local.get $principal) (local.get $blob))
                (then (call $attest))
            )
            ;; Cleanup
            (call $signer_drop (local.get $signer))
            (call $principal_drop (local.get $principal))
            (call $signature_drop (local.get $sig))
            (call $blob_drop (local.get $blob))
        )
        (start $start)
    )
    (core instance $i (instantiate $m
        (with "env" (instance
            (export "attest" (func $attest_lowered))
            (export "generate-signer" (func $generate_signer_lowered))
            (export "get-blob" (func $get_blob_lowered))
            (export "signer-principal" (func $signer_principal_lowered))
            (export "signer-sign" (func $signer_sign_lowered))
            (export "sig-verify" (func $sig_verify_lowered))
            (export "signer-drop" (func $signer_drop))
            (export "principal-drop" (func $principal_drop))
            (export "signature-drop" (func $signature_drop))
            (export "blob-drop" (func $blob_drop))
        ))
    ))
)
